### PR TITLE
Update for scipy 1.4

### PR DESCRIPTION
**Pull request by Ericgig**
Leftovers from #1144

### CODE REVIEW

**Comment by nathanshammah** [comment]
My bad

**Comment by Ericgig** [comment]
@nathanshammah Ready. You can review and merge.

**Comment by nathanshammah** [comment]
Why did you switch from scipy to numpy for rand? It all looks fine to me.

**Comment by Ericgig** [comment]
Scipy rand will be deprecated in scipy 2. Warning are present in 1.4

**Comment by nathanshammah** [comment]
Should we change also [`requirements.txt`](https://github.com/qutip/qutip/blob/master/requirements.txt)? Should I change then also the qutip-tutorials for Binder to scipy==1.4?

**Comment by Ericgig** [comment]
No. This does not affect requirements.

**Pull request merged**
