### PR TITLE
Fix hinton plot displaying rho.T instead of rho

### LINKED ISSUE #2009: `visualization.hinton` plots matrix transpose instead of matrix
### Bug Description

The `hinton` visualization method plots the transpose of the matrix instead of the matrix itself.

### Code to Reproduce the Bug

```shell
import qutip as qt
u = qt.Qobj([[1.0, 1.0],
             [0.0, 1.0]])
qt.hinton(u)
```

### Code Output

_No response_

### Expected Behaviour

Output:
7c46ebe9-df8a-4246-898c-adb88b07fd01

Expected:
eeda621e-7720-42bd-b320-19ac9f2dc772

### Your Environment

```shell
QuTiP Version:      4.7.0
Numpy Version:      1.23.1
Scipy Version:      1.9.0
Cython Version:     None
Matplotlib Version: 3.5.2
Python Version:     3.9.9
Number of CPUs:     8
BLAS Info:          OPENBLAS
OPENMP Installed:   False
INTEL MKL Ext:      False
Platform Info:      Darwin (arm64)
```

### Additional Context

I am happy to help fixing this if you confirm the issue.

### PR DESCRIPTION
**Pull request by PierreGuilmin**
**Description**
Fix the hinton visualization method to plot the matrix instead of its transpose.

**Related issues or PRs**
Fix #2009.

### CODE REVIEW

**Review by Ericgig — CHANGES_REQUESTED** [review]
The tick label also need to be switched.

**Comment by PierreGuilmin** [comment]
I'm not sure why? See for example the proposed correction in issue #2009, I don't understand why we'd have to modify the ticks label.

**Comment by Ericgig** [comment]
If you do 
`sigmap = qt.basis(2,0) @ qt.basis(2,1).dag()`
You see that the point is at `|0><1|` as expected.
image

With these changes, the mark is situated at `|1><0|`:
image

**Comment by PierreGuilmin** [comment]
I think the second plot is actually the right one 🤔 

```python
>>> qt.basis(2,0) * qt.basis(2,1).dag()
[[0. 1.]
 [0. 0.]]
```

Or directly:
```
   (0 1)
(1)(0 1)
(0)(0 0)
```

I agree the operator writes $\ket{0}\bra{1}$, but usually when plotting a matrix we plot its _action_ on the columns elements, and indeed $\ket{0}\bra{1}(\ket{0})=0$ and $\ket{0}\bra{1}(\ket{1})=\ket{0}$. Should we remove the kets and bras symbols in the labels? They are quite confusing.

**Comment by PierreGuilmin** [comment]
So you mean switching the horizontal x-axis labels to $\bra0$, $\bra1$ and the vertical y-axis labels to $\ket0$, $\ket1$?

**Comment by Ericgig** [comment]
Yes, switching the x-axis and y-axis labels.

**Comment by PierreGuilmin** [comment]
Sorry for the delay @Ericgig 🙇‍♂️

**Review by Ericgig — APPROVED** [review]
Look good, thank you.

**Pull request merged**
