### PR TITLE
Stinespring dilations of type="super" Qobj

### PR DESCRIPTION
**Pull request by cgranade**
This feature starts work towards implementing diamond norms between quantum channels by providing Stinespring dilations of ``type="super"`` Qobjs. This requires generalizing the current ``to_kraus`` feature, since the left and right Kraus operators are the same only for CP maps, whereas the arguments to diamond norms are very often not CP (in particular, will often be a difference, || \Lambda_1 - \Lambda_2 ||_\diamond).

The pull request is currently in an incomplete state, so as to solicit feedback before solidifying the design. The docstrings are missing or are incomplete, Python 3 compatibility has not yet been tested, and I still need to make unit tests. Most importantly, the ``dims`` attribute of the input Qobj is not yet preserved, in lieu of solving #331.

### CODE REVIEW

**Comment by cgranade** [comment]
As a quick addendum, [this notebook[(http://nbviewer.ipython.org/gist/cgranade/d41a9147498bbe82ff2a) serves as a rough demonstration of the new functionality implemented by this PR.

**Comment by cgranade** [comment]
This PR should now preserve dimensionality of its arguments, has better documentation, and is now covered by several unit tests. Next, I'll make sure that I've got it working for Python 3.

**Comment by nonhermitian** [comment]
I think some documentation for this would also be nice.  Especially since I am by no means familiar with what you are doing.  I am planning on rewriting the docs using IPython notebooks for version 3.3, so perhaps a notebook detailing the background and usage of these quantum channel features could be implemented then.

**Comment by cgranade** [comment]
Sounds good, I'll get on that, then, and make that a PR to qutip-notebooks. Roughly, this produces a pair of partial isometries representing a quantum channel that are quite useful for some theory work. For instance, [Watrous showed that](http://theoryofcomputing.org/articles/v005a011/) the diamond norm can be expressed in terms of a semidefinite program parameterized by the Stinespring dilation. It's that application in particular that motivated me to get this working, as computing diamond norms would be very useful to a wide range of different quantum information projects.

**Comment by cgranade** [comment]
I apologize for my distraction, but I fixed the Python 3.4 failures now. Is there anything else that I should do before this is ready to merge? Thanks!

**Comment by ajgpitch** [comment]
It seems fine to me. The technical and documentation issues appear to have been addressed

**Comment by jrjohansson** [comment]
Looks good and ready to merge.

**Comment by ajgpitch** [comment]
I see that this PR now has conflicts @cgranade are you able to look into this

**Comment by cgranade** [comment]
I think this should fix the merge conflicts, as all of the new tests now pass. Sorry for the hassle!

**Pull request merged**
