### PR TITLE
Solver contain unique integrator 

### PR DESCRIPTION
**Pull request by Ericgig**
**Description**
`Solver` create the integrator at `__init__` instead of in `run` and `start`.
`step` and `run` no longer take an `options` parameter.  `solver.options = new_options` will now reset the integrator to use the new options. However changing options will always reset the integrator.

**Related issues or PRs**
Similar improvement where first made in #1710, splitting it to made that PR simpler.

**Changelog**
Sovlers manage options as a property instead of method's parameter.

### CODE REVIEW

**Comment by hodgestar** [comment]
This looks great and I think it will help a lot in cleanly implementing more complex solvers light the HEOMSolver. I have two suggestions for future improvements:

- I'd like to see `.options = ...` become a method because it now modifies the existing integrator and `.options(...)` would both make that clearer and more flexible. E.g. with a method we could allow both `.options(new_options)` to completely override the options and `.options(key=new_value)` to update just one setting.

- The first call to `result.add(t, X)` uses `X = state0` but state0 could be almost anything the user passed in (and not necessarily the canonical form returned by `_restore_state`). It would be better if either there was a separate method to override to convert `state0` into the canonical form, or `result.add(t, X)` was called initially with `X = _restore_state(_data0)`.

**Comment by Ericgig** [comment]
@hodgestar, I consider the second point as a bug.
Do you want me to fix it here or do it elsewhere? (and add swap-able `Result` while at it?)

The options method will wait for what will become of #1812.

**Comment by hodgestar** [comment]
> @hodgestar, I consider the second point as a bug. Do you want me to fix it here or do it elsewhere? (and add swap-able `Result` while at it?)

Happy for you to fix it here if it doesn't complicate things too much. It was a bug before this PR though, so also happy for it to be fixed later.

**Comment by Ericgig** [comment]
The fixes are quite simple, added them here.

**Review by hodgestar — APPROVED** [review]
Thanks!

**Pull request merged**
