### PR TITLE
Travis CI tests - Specify blas type in conda env create

### PR DESCRIPTION
**Pull request by ajgpitch**
blas=*=mkl for Intel MKL
blas=*openblas for openblas

### CODE REVIEW

**Comment by ajgpitch** [comment]
As mentioned in #872 the MKL builds are currently installing with openblas numpy.
This implements the suggestion from
ContinuumIO/anaconda-issues#9519
Initial local tests look fine

**Comment by ajgpitch** [comment]
Python 2.7 builds failed. Assuming this is because the blas module does not exist.
See commit message for details of this new attempt

**Comment by ajgpitch** [comment]
This looks like it's gonna pass. I check two of the tests and the MKL directive was successfully followed.
Happy for this to be merged.

**Comment by ajgpitch** [comment]
So one of the metrics dnorm tests failed in the MKL=0 OPENMP=1 combo. I cannot see why.
I have tried restarting the tests

**Comment by sahmed95** [comment]
Is this a temporary solution? Ready to be merged?

**Comment by ajgpitch** [comment]
I think that it may not be necessary when the Anaconda people have fixed the problems they mention in
ContinuumIO/anaconda-issues#9519
However, I think it will continue to work, so this could be considered a permanent change.
It's ready to merge.

**Comment by ajgpitch** [comment]
Merging this now, as I want to get some other PRs testing

**Pull request merged**
