### PR TITLE
Improved Random Quantum Objects

### PR DESCRIPTION
**Pull request by cgranade**
This PR addresses #315 by providing sampling for Haar (unitary), Hilbert-Schmidt (DMs), Ginibre (DMs) and BCSZ (superoperators) distributions. Some more documentation is needed still, but the tests pass locally on Python 2.7 and 3.4.

### CODE REVIEW

**Comment by cgranade** [comment]
I just noticed that this PR treats the dims keywords differently than the existing ``rand_*`` functions, and does not accept a list. I will extend this PR to include that functionality soon.

**Comment by cgranade** [comment]
The new and existing functions now share a uniform API, with each taking an ``N`` and a ``dims`` argument. Since ``rand_ket`` did not currently respect ``dims`` due to a bug in ``check_dims``, I modified that function and ``rand_ket_haar`` slightly and added unit tests to check that they act uniformly. The new tests run fine for me locally, so I'm happy for with this PR if the Travis build works. Thank you!

**Comment by jrjohansson** [comment]
Thanks for this PR. It is looking very good.

**Comment by cgranade** [comment]
Glad to be of service. Anything other than the usual documentation and
notebook you would like to see? Thanks!

**Comment by jrjohansson** [comment]
Updated docs + example notebook would be great. Thanks, merging this now.

**Pull request merged**
