### PR TITLE
Adds input and output states to `QubitCircuit`

### PR DESCRIPTION
**Pull request by sahmed95**
This is an attempt to solve #678. The `QubitCircuit` class now has a method to add input and ouput states to a circuit. By default, all inputs and outputs are initialised to None. A new input state can be added similar to adding a gate by using the new function `add_state`. The user can specifying the state, the list of qubits where it should be added and the `state_type` as `input` or `output`.

States can be anything provided they are entered as a string.
```
qc = QubitCircuit(3)
qc.add_state("0", targets=[0])
qc.add_state("+", targets=[1], state_type="output")
qc.add_state("-", targets=[1])
```

### CODE REVIEW

**Comment by sahmed95** [comment]
@ajgpitch Hi, this adds input and output states to the QubitCircuit class. The next bit is to get the latex circuit visualisation for this. I will get that working as soon as I can. I guess there is not testing for that and I have to check it by trying out different plots. The next bit will be to get a list of known states and create a map so that they can be converted to a proper `Qobj`. Finally, we should have a method in `QubitCircuit` to calculate the output states, given an initial input state and add it to the circuit. But, I guess I could work on that in a different PR. All this is dicussed in the orginal issue #678

**Comment by sahmed95** [comment]
Hi, this is ready for review. We now have the option to add input states to a circuit and the visualisation for the same. If the particular wire does not have an input, it is ignored.

Circuit with all input states defined

screen shot 2017-04-04 at 11 00 51 pm

Circuit with only one input state

screen shot 2017-04-04 at 11 04 28 pm

**Comment by mortenkjaergaard** [comment]
This is great, thank you! 

Would it possible to instead of just accepting strings, it would also be able to accept LaTeX code when defining the state? E.g. often you'd want to send in a state $\psi_\text{in}$ and have a state $\psi_\text{out}$?

**Comment by sahmed95** [comment]
Hi @mortenkjaergaard. Thanks for the suggestion. This code is "latex proof" as in any valid latex code can be directly passed for defining the state. Have a look at the following. You don't have to use the dollar sign as qcircuit takes care of it.

screen shot 2017-04-05 at 3 50 10 am

**Comment by mortenkjaergaard** [comment]
Fantastic @sahmed95! I would love to know how to pull this into my own release of QuTiP. But potentially this is not something we should discuss here in this thread?

Thanks again for the swift and beautiful resolution 👍

**Comment by sahmed95** [comment]
Well the most naive way I can think of is to overwrite the `circuit.py` file in your local installation of qutip with this new `circuit.py` file. It is located in `qutip/qutip/qip` in your local python package installation folder. If you can't find it then you can go for a fresh install with this file

- Remove your current qutip version with a `pip uninstall qutip`
- Download the latest qutip version from the [website](qutip.org) and replace the `circuit.py` file in `qutip/qip` folder with the one from here.
- Reinstall qutip by running `python setup.py install` from your qutip folder.

Of course there are better ways to do this such as pulling this branch locally and updating your qutip version. If you need any help ping me on our gitter channel https://gitter.im/qutip/Lobby.

**Comment by ajgpitch** [comment]
This looks really good to me. I am happy to merge it now if @sahmed95 is happy with that

**Comment by ajgpitch** [comment]
@mortenkjaergaard once merged there are documented procedures for you to install the latest version from this repo

**Comment by mortenkjaergaard** [comment]
@ajgpitch great, yes, those I am familiar with. If you choose to to merge this, it will be even easier to update my qutip. Thanks!

**Comment by sahmed95** [comment]
You can go ahead and merge it. The tests are passing and I checked the
latex code and visualization myself.

**Comment by mortenkjaergaard** [comment]
Hi again @ajgpitch and @sahmed95.

I had a chance to work a little with the ".add_state" feature this morning, and wanted to raise an issue in terms of the visualization. The problems are shown in the figure below:
image
(NB: this could just be due to jupyter notebook? In any case, I see the problem is also reproduced in @sahmed95's post here: https://github.com/qutip/qutip/pull/679#issuecomment-291652067)

Two things:
1) The cropping seems to go bonkers if you use anything else than one symbol in the ket-state
2) It's not possible to use \textrm{xxx} in the ket-names.

**Comment by sahmed95** [comment]
Hi, the cropping issue was there before. Even I had faced it when
visualizing circuits. I used to just add a redundant qubit to the circuit
to get that extra padding. I ll look into the cropping and resize it to
make the visualization better. Could you please open a new issue for that?

**Pull request merged**
