### PR TITLE
4.3 release

### PR DESCRIPTION
**Pull request by sahmed95**
It is about time that we made the 4.3 release, @ajgpitch @nonhermitian. Could you please check and merge this? I will build the 4.3 dist and the documentation and then update pip and the conda-forge version. We have the new scattering module and PIQS in this version.

### CODE REVIEW

**Comment by ajgpitch** [comment]
Looks fine to me. I suppose we should wait for tests to pass.
@sahmed95 go ahead and merge, if I don't get there first

Remember to bump up the master version too.
I assume you are following:
https://github.com/qutip/qutip-doc/blob/master/release_distribution.rst

**Comment by sahmed95** [comment]
Yes, I am following that. Bumping master to 4.4.

**Comment by ajgpitch** [comment]
One fail in some rand test. Just outside tolerance
Merging anyway

**Comment by sahmed95** [comment]
Thanks. I was thinking of restarting the build. Since the PR for the bump worked out just fine (#890), I guess this is okay. Making a new release now.

**Pull request merged**
