### PR TITLE
Rand updates

### PR DESCRIPTION
**Pull request by nonhermitian**
- Added random stochastic operators.

- rand_herm and rand_dm can be passed an array of eigenvalues that will be the eigenvalues of the resulting random operators. This is done via complex Jacobi rotations, but is really only suitable for operators with dimensionality <~=1000.

- Added unit tests.

### CODE REVIEW

**Comment by ajgpitch** [comment]
Looks good to me.
You'll see one test has passed and another not. I am not sure what the difference is between these, and why one would fail and the other not?

**Comment by nonhermitian** [comment]
That is a test for super operators that fails quite often.  It is unrelated to the current PR.  In fact, I think I will submit an issue to Chris about this particular test.

**Comment by nonhermitian** [comment]
I am rerunning the tests that failed.  Should pass unless we get unlucky twice.

**Comment by nonhermitian** [comment]
All good now.

**Comment by cgranade** [comment]
I think this all looks good. As for the failing test, please see #420. I think that should do it.

**Comment by nonhermitian** [comment]
Merging this.

**Pull request merged**
