### PR TITLE
Entropy vn dicke

### PR DESCRIPTION
**Pull request by nathanshammah**
Addressing #993: nonlinear functions such as the Von Neumann entropy or purity of a density matrix written in the Dicke basis need to account for the identical copies of the blocks relative to non-symmetrical Dicke states. 

This can be done by cycling into the blocks and applying the correct weight accounting for degeneracy (using `piqs.state_degeneracy`). 

This PR also contains auxiliary functions to visualize and unpack the Dicke-basis density matrix into the full 2^N space still of collective spin but with degenerate blocks. 

It uses the `purity` method proposed in #1045. 

Will add info in User Guide and notebooks to highlight this features that need to be considered to correctly calculate nonlinear functions of a density matrix in the Dicke basis.

### CODE REVIEW

**Comment by nathanshammah** [comment]
In the latest commit I refactored the `entropy_vn_dicke` and  `purity_dicke` functions in terms of a more general function, `dicke_trace`, which accounts for adding with the correct weight the blocks of a density matrix in the Dicke basis. The `dicke_trace` function can be used by other similarly nonlinear functions that involve taking the trace of a Taylor-expandable function.

**Comment by quantshah** [comment]
Thanks Nathan. Lets see if the tests pass. Meanwhile, perhaps you could do `black -l 79` to keep the lines only 79 characters long. Also there are some trailing white spaces and spaces in a blank line which seem not to be picked up by black. Could you please quickly check that so that we get the code climate green check? If not then we can still merge this.

**Comment by nathanshammah** [comment]
@quantshah: what about if we make a PR uniforming all code in QuTiP with `black` and automatically enforce  also the 79 line limit? Also, what about adding it to the guidelines for contributions?

**Comment by quantshah** [comment]
I am not completely familiar with black yet and how much it adheres to pep8 so I will keep that for a big PR some other time. Right now we can slowly start blacking our code for the new modules. 

This PR passes all the tests so I will be happy to merge.

**Comment by quantshah** [comment]
@nathanshammah Could you please also take care of the "blank line contains spaces" issues from code climate?

**Pull request merged**
