### PR TITLE
WIP: Citation message and bibtex generator

### PR DESCRIPTION
**Pull request by sahmed95**
As discussed in #664 this PR is regarding citation reminders for QuTiP as it seems that many times users are unaware of the papers to cite when they use QuTiP.

I have added a bibtex file in the source now and into the MANIFEST file. We should discuss how to get this to the users attention. Creation of a cite() function which generates a bibtex entry in the working directory whenever qutip is imported could be one option. The other option is to put it in /home/qutip or print it out whenever a result class is called. We can also add a welcome message at setup which reminds users regarding the papers and points them to the bibtex file.

I am in favour of having a bibtex generator in __init__.py such that qutip.bib appears in the code folder whenever QuTiP is used.

### CODE REVIEW

**Comment by ajgpitch** [comment]
It would be good to include the zenodo bib reference that relates to the specific version that is being used. It would be good if users included this zenodo reference, as this pinpoints a version, which could be important for people trying to repeat the results.

In the same vein it could be a good idea to automatically output a file into the cwd that contains the `qutip.about()` output. We could include a citation reminder in the `qutip.about()` and also a message that explains that bib files have also be produced for their convenience.

In order to placate those who may object to all of this, we should provide some setting that allows users to turn off this bib and about() output. We should mention this setting in the `about()`

We also need to handle file errors that may occur.

**Comment by ajgpitch** [comment]
We should avoid any file output related to Result objects. This could be costly in loops that produce a lot of results.

**Comment by sahmed95** [comment]
Hi, we have the cite function in `qutip.about` now and can decide when to invoke it. I don't think users usually call the `about` function much so it may not be very effective to use it there. The current `cite` function generates a qutip.bib` file and prints it out. If the filename is not specified, it creates a `qutip.bib` file in cwd.

**Comment by sahmed95** [comment]
@nonhermitian The test failure is with NOMKL=1 and OPENMP=0. Specifically, a solver is unavailable. This is not related to the addition of this function. Something else is breaking.

```
cvxpy.error.SolverError: Solver 'CVXOPT' failed. Try another solver.
```

**Comment by sahmed95** [comment]
@Phyks Thanks for the suggestion. I made the qutip.cite() function to print and generate a bibtex file. Perhaps this is sufficient. With a message during install mentioning that you can invoke"
```
from qutip.about import cite
cite("path_to_generate_bibtex")
```
to get the bibtex file and printing the output on the screen. @ajgpitch Should I add this to the setup.py file. Can we move this PR forward?

**Comment by ajgpitch** [comment]
@sahmed95 what are you thinking is needed in setup.py

**Comment by ajgpitch** [comment]
I don't think we should print the whole bibtex content to screen by default when calling about(). I think a message to say.
"Please cite QuTiP in your publication - for you convenience bibtex file saved to:\n".join(filepath)

I think really we should provide some way to turn off the saving of the bibtex file in settings as well

**Comment by ajgpitch** [comment]
I think it would be better if the article names were 'qutip1' and 'qutip2' rather than 'Johansson2013' and 'Johansson2012'

**Comment by sahmed95** [comment]
In the current code there is no automatic generation of the bibtex files but a polite message to cite qutip and use the cite function to generate the same. I hope that is okay.

```
print("Please cite QuTiP in your publication - for you convenience a bibtex file can be easily generated using `qutip.about.cite()`"
```

**Comment by ajgpitch** [comment]
Ok, I think I get it now. Seems good to me.
I did a few tiny edits. If all tests are good and @sahmed95 happy with my edits, then I will merge

**Comment by sahmed95** [comment]
Thanks for taking a look. This is good for me and you can merge it once the tests pass. Thank you.

**Pull request merged**
