### PR TITLE
initial implement on perturbation theory

### PR DESCRIPTION
**Pull request by zasdfgbnm**
initial implement, waiting for the review of upstream
The notebook that describe everything in detail is https://github.com/qutip/qutip-notebooks/pull/12

### CODE REVIEW

**Comment by jrjohansson** [comment]
Thanks a lot for the update! Could you please add few unit tests for this module, perhaps based on some of the examples from your notebook?

**Comment by zasdfgbnm** [comment]
Hi, I'm now still working on cleaning the codes, make them better documented and making the notebook more clear. After I finished everything, I will push my job to github and leave a comment here.

**Comment by zasdfgbnm** [comment]
Hi, I have updated the interface to make it much much easier to use. And, I added the unit test and now the test will succeed. The test is the following: generate random Hamiltonians and run perturbation and see whether the energy levels match with the exact solutions. I have done all I want to do up to now. So, please review these codes again and consider merging them.

**Comment by nonhermitian** [comment]
Closing this given the age of this.

**Pull request closed without merging**
