### PR TITLE
Marked test

### PR DESCRIPTION
**Pull request by Ericgig**
Mark some of the slower test to be skipped when running.

`qutip.testing.run()`: about 5 min.
`qutip.testing.run(full=True)`: about 30 min.

Keep test for every function: stochastic only test the default solver... 
Also speed up some test by limiting the tests (shorter time for solver, less "pixel" for wigner).

Build on top of #1131, must be merged after that PR.
Should solve #1147

### CODE REVIEW

**Comment by nathanshammah** [comment]
No cython tests are failing.

**Comment by Ericgig** [comment]
The fix for the no cython should go in #1131, I sent the fix directly to @tehruhn :  tehruhn/qutip#1

**Comment by nathanshammah** [comment]
Need to resolve conflicts here.

**Comment by nathanshammah** [comment]
Can we add information about this feature in the documentation?

**Comment by Ericgig** [comment]
I added the feature explanation in the docstring. I don't think we have special documentation for `testing.run`.

**Pull request merged**
