### PR TITLE
Br in correlation function

### PR DESCRIPTION
**Pull request by IIAOPSW**
this was the other half of the fork that I just finished rebasing into its own branch.

### CODE REVIEW

**Comment by ajgpitch** [comment]
@IIAOPSW Could you just remind us here what we are doing with this PR please

**Comment by ajgpitch** [comment]
Some initial feedback:
There are a number of lines that overrun the pep8 limit

**Comment by ajgpitch** [comment]
@IIAOPSW I cannot actually find your original PR, so lets make like it never happened. Edit the first comment to give some background on this.

**Comment by IIAOPSW** [comment]
The original was #785 which auto-closed when I deleted the branch and rebased to split it into 2. I'm just undoing my branch management sloppiness. 

This was about the correlation function supporting bloch-redfield solver.

**Comment by ajgpitch** [comment]
Will check and fix any pep8 issues, then merge

**Comment by hodgestar** [comment]
@Ericgig Do you think it's a good idea to add the br_solver as an option for the correlation functions? If so, there a plan to make selecting a solver more flexible in QuTiP v5? I found https://github.com/qutip/qutip/projects/6#card-72925447 which suggest there might be, but I don't know the full plan.

**Comment by Ericgig** [comment]
We don't need to add `br_solver` as a correlation option, I think we can already do it by passing a bloch redfield tensor as `H` and  using `solver="me"`.  
The plan for v5 is a simple cleaning as it still calls `cython_build_cleanup` and `rhs_clear` which don't do anything anymore.

**Comment by hodgestar** [comment]
In that case I think I will close this for now -- please shout if it needs to be reopened.

**Pull request closed without merging**
