### PR TITLE
Remove Qobj.__array__ for numpy 1.20 compatibility

### PR DESCRIPTION
**Pull request by jakelishman**
Proposed solution to #1433.  See that issue/commit logs for more details on this PR.

### CODE REVIEW

**Review by hodgestar — APPROVED** [review]
The change looks good to me.

Did any of the QuTiP tests break? If no, that is quite encouraging because it suggests that a large codebase using QObj might not be affected at all.

I think we need to document somewhere (perhaps in the release notes of documentation on Qobj) what a use should do if they were relying on `__array__` (i.e. call `.full()` explicitly themselves).

**Comment by jakelishman** [comment]
Actually I'm going to close this for now pending further discussion on #1433.  The failing tests are using the implicit array coercion, which we may or may not want, but regardless, there's a bigger decision to be made.

**Comment by ajgpitch** [comment]
I think Michael Goerz suggested adding this as it is somehow helpful for
his krotov package

**Comment by jakelishman** [comment]
He did - he's the original feature requester, but given super super weird interactions with ufuncs (see #1433), it's not so clear to me that it was _necessarily_ the right idea to implement especially now it's causing problems with how numpy arrays are used in the library.  There always was a work-around; allowing `np.array(qobj)` was more to save him from writing `x = x.full() if isinstance(x, Qobj) else np.asarray(x)`.

That said, I came round to the idea more as I read more about the control we can have over the rest of the numpy infrastructure.  We can allow `np.array` on `Qobj` (satisfying Michael's original request), and with a little bit of extra code we can prevent all the super weird ufunc/implicit casting behaviour, because `Qobj` shouldn't be able to implicitly interoperate with raw arrays.  I know in my personal code I'd rather use `Qobj.full()`, but I no longer think it's _wrong_ to allow `np.array(qobj)` given that other people like it, even with these numpy 1.20 problems.  It does make it difficult to put `Qobj` in arrays, but numpy 1.20 has ruled out being able to have `np.array(qobj)` and `np.array([qobj1, qobj2], dtype=object)`, so that's not really our fault.

**Comment by ajgpitch** [comment]
> but numpy 1.20 has ruled out being able to have np.array(qobj) and np.array([qobj1, qobj2], dtype=object)
Sorry, @jakelishman please clarify. Numpy 1.2 does not allow for arrays of objects? Seems strange. I some recollection doing this sometime, I am hoping it's not in qutip.control :/

**Comment by ajgpitch** [comment]
Maybe @goerz wants to comment on these ideas?

**Comment by jakelishman** [comment]
Best to move further discussion to #1433, which is the main issue for this, since this PR is closed pending a decision over there.

**Pull request closed without merging**
