### PR TITLE
Dev uhack solver docs

### LINKED ISSUE #2163: Solver options
### Problem Description

The options that can be passed to the solvers are not entirely clear by looking at the documentation. For example:
image
Does not show the explicit options even thought it refers to them in the parameter documentation. For comparison, SESolver does show the options.

This I assume is because the options are inherited from SESolver. But this is not clear either by looking at `MESolver`'s rendered documentation.
image

When using `help(MESolver)` the documentation of the class is much clearer but perhaps too verbose for the online documentation.

### Proposed Solution

I would suggest we render the options property explicitly for each solver. I would also consider rendering the documentation related to the `run` method. If not, we should render at least `Solver` documentation which does not seem to be listed in the class API documentation for solvers.

Affected solvers:
- [ ] MESolver
- [ ] SMESolver
- [ ] SSESolver
- [ ] NonMarkovianMCSolver

### Alternate Solutions

_No response_

### Additional Context

The documentation was taken from qutip 5.0 "ReadTheDocs".

### PR DESCRIPTION
**Pull request by EmilianoG-byte**
**Description**
Add inherited members (properties and methods) in the API docs for the solvers mentioned in the issue.
Add inheritance of these solvers showing from which base classes they inherit.

**Related issues or PRs**
fixes #2163

### CODE REVIEW

**Comment by EmilianoG-byte** [comment]
I had also the idea that showing from which base classes these solvers inherit would be enough, but since the issue asks to show `property` and `run` explicitly on each of the solver docs, then I opted do to it this way.

Also, from my implementation, also other methods are now documented (e.g. add_integrator).  Which I believe since these are public methods, they should be documented as well (?)

**Comment by EmilianoG-byte** [comment]
I see there is an error when building the pdf but don't understand why. Running the `make pdflatex` command works for me locally. Also the html page is rendered as expected:

Screenshot 2023-05-29 at 11 56 07

**Comment by BoxiLi** [comment]
In the CI test, we convert warnings to errors. Have you tried `make latexpdf -W`?

**Comment by EmilianoG-byte** [comment]
I just ran locally:
`make latexpdf SPHINXOPTS="-W --keep-going -T"`
And got `build succeeded` message.
The error on the project pipeline shows:
 `Unknown interpreted text role "cls".` for the `me_solver`.

Do you have an idea of why could this be happening?

**Comment by EmilianoG-byte** [comment]
resolved 😄 !

**Review by Ericgig — APPROVED** [review]
Looks good, `options` property is properly displayed for all solver, thank you.

**Comment by EmilianoG-byte** [comment]
Awesome :D, do I just close the PR then?

**Comment by Ericgig** [comment]
No, we will merge it.

**Review by AGaliciaMartinez — CHANGES_REQUESTED** [review]
Thanks for the PR! At the begining I was thinking to include only the `run` and `options` method but I think including all the other ones is also fine. However, I do think that if we are including all methods we should do so consistently for all the classes. This would require to do the same changes you have done to the rest of the classes to `SESolver` and `MCSolver`. After that I think the PR is ready to Merge. Thanks again for the changes!!

**Review by AGaliciaMartinez — APPROVED** [review]
Thanks for the changes!

**Comment by EmilianoG-byte** [comment]
Thank you for the comments! 

Also, as someone who uses QuTip on a daily basis as part of my work, I was really happy with the changes and restructuring of the solver module. Thank you for the work 😄 

If I may take this opportunity to ask two things:
* I have been looking on Qutip 4.7 for ways to speed up the mc solver simulations, and one of them was to not compute the average density matrix for all times, but only for the last time. Since the behaviour at 4.7 of `mcsolve` was to average the state anyways (despite what I passed on the options object), I found a workaround by having an independent list to create my time dependant Hamiltonian and the `tlist` argument of the solver. Is this something achievable more straightforwardly/differently in Qutip 5.0?
* (shorter): Is there a roadmap for when will Qutip 5.0 be released?

Thank you for your time, and I hope its fine me asking here 😆

**Comment by EmilianoG-byte** [comment]
Btw, there seems to a small bug. When running:

```
from qutip.solver.mcsolve import MCSolver, mcsolve
import numpy as np
from qutip import tensor, fock, qeye, destroy

times = np.linspace(0.0, 10.0, 200)
psi0 = tensor(fock(2, 0), fock(10, 8))
a  = tensor(qeye(2), destroy(10))
sm = tensor(destroy(2), qeye(10))
H = 2*np.pi*a.dag()*a + 2*np.pi*sm.dag()*sm + 2*np.pi*0.25*(sm*a.dag() + sm.dag()*a)
data2 = mcsolve(H, psi0, times, [np.sqrt(0.1) * a])
data2.states[0]
```
The output is not rendered in latex bur rather shows the raw code:
Screenshot 2023-06-02 at 01 37 59

In case you want  to create an `issue` for it, perhaps.

**Comment by BoxiLi** [comment]
It looks like VSCode with Jupyter notebook terminal. I also have this problem. We had this issue solved once in https://github.com/qutip/qutip/pull/2017 but it seems to be back again. You are very welcome to open a separate issue for this.

**Comment by EmilianoG-byte** [comment]
I have added the issue. I have spotted already some suggestions of what can be going wrong and note them down on the issue details!

**Comment by EmilianoG-byte** [comment]
Also, @Ericgig please let me know if you have time to answer my question regarding the MC solver. I would greatly appreciate it😄

**Comment by EmilianoG-byte** [comment]
@Ericgig, I see. Thank you so much! I had the impression that v5 would change something related to the calculation of density matrices being more flexible. But all in order now. Thank you!

**Pull request merged**
