### PR TITLE
Move tests to pytest

### PR DESCRIPTION
**Pull request by jakelishman**
To get more familiar with bits of the internals, I'm going through and migrating the tests to `pytest`.  While I'm at it, I'm also fixing PEP8 issues in the testing files, since CodeClimate will moan at me if I don't.

I'm basically learning how to use `pytest` and how to code as part of an organisation as I go, so please feel free to correct me if I'm doing something wrong.

I'll leave this PR as in draft mode until I've made it through more of the testing files.

### CODE REVIEW

**Comment by nathanshammah** [comment]
This could be ready and be part 1 of a part 1 and part 2 project, in order to start merging, if missing tests are independent on these.

**Comment by jakelishman** [comment]
Yeah, sure, though parts one through fifteen might be more appropriate - there's a lot of tests.  I'll rebase this branch onto master first, though, since I think there will be some merge conflicts after the merging of #1151.

**Comment by jakelishman** [comment]
Ok, it's rebased onto master as of 663523e, so it should currently merge without conflicts, and I've ensured that all the tests in `test_brmesolve_td.py` that Eric marked as slow have had that mark maintained in this new format.

**Comment by jakelishman** [comment]
To convert more files, shall I continue to push to this PR, or should I open a new one?  I'm not overly familiar with github.

**Comment by nathanshammah** [comment]
A new one. Thank you a lot.

**Pull request merged**
