### PR TITLE
Update documentation builds to Sphix 6.1 and matplotlib 3.7

### PR DESCRIPTION
**Pull request by hodgestar**
**Description**
Our documentation was being build with a ludicrously outdated version of Sphinx. This updates the builds to use the current Sphinx and matplotlib versions.

**Related issues or PRs**
- None

### CODE REVIEW

**Comment by hodgestar** [comment]
@jakelishman I just pinged you for fun and because I though you might like to see the QuTiP documentation builds being dragged into the century of the fruit bat. :)

**Comment by jakelishman** [comment]
Hahaha, thanks!  One of the earlier things I did on Qiskit was to get the docs building with current Sphinx (4, at the time) too - we had found a couple of bugs in extensions that I then patched, and we needed to be on latest Sphinx to use them.  You'll be ahead of us if you're up to Sphinx 6 - we still have a UI toolkit dependency that limits us (unnecessarily) to Sphinx 5 right now.

**Review by Ericgig — COMMENTED** [review]
Not sure why, but I have trouble downloading opening HTML documentation from the artifact...
I will re-run the doc build to see if it change anything.

Is it needed to fix all version up the the micro release?

**Comment by hodgestar** [comment]
> Not sure why, but I have trouble downloading opening HTML documentation from the artifact... I will re-run the doc build to see if it change anything.

The download worked for me and the HTML and PDF docs look okay.
 
> Is it needed to fix all version up the the micro release?

This PR doesn't change that. We fix the version to micro releases to ensure that the documentation builds don't fail or do odd things without us noticing.

**Comment by hodgestar** [comment]
@Ericgig Thoughts on this? Can we merge it?

**Review by Ericgig — APPROVED** [review]
Looks good.

**Pull request merged**
