### PR TITLE
Preserve superrep in Qobj.dag().

### PR DESCRIPTION
**Pull request by cgranade**
This PR introduces a fix for #374.

### CODE REVIEW

**Comment by cgranade** [comment]
To guard against regression on this, I would like to add unit tests covering adjoint channels before merging, since that's where I first noticed this issue. I will try to do so soon.

**Comment by ajgpitch** [comment]
Seems like a good fix. Can't see any risks.

**Comment by cgranade** [comment]
I apologize to all for the delay, but I just added checks for regression on this issue. They currently fail due to a problem with ``to_chi`` and multiple qubits.

```python
======================================================================
ERROR: Failure: TypeError (Incompatible Qobj shapes)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Anaconda\lib\site-packages\nose\loader.py", line 251, in generate
    for test in g():
  File "C:\Users\Chris\Dropbox\software-projects\qutip\qutip\tests\test_qobj.py", line 671, in test_dag_preserves_superrep
    yield case, to_chi(qobj)
  File "C:\Users\Chris\Dropbox\software-projects\qutip\qutip\superop_reps.py", line 435, in to_chi
    return to_chi(to_choi(q_oper))
  File "C:\Users\Chris\Dropbox\software-projects\qutip\qutip\superop_reps.py", line 432, in to_chi
    return choi_to_chi(q_oper)
  File "C:\Users\Chris\Dropbox\software-projects\qutip\qutip\superop_reps.py", line 258, in choi_to_chi
    return Qobj(B.dag() * q_oper * B, superrep='chi')
  File "C:\Users\Chris\Dropbox\software-projects\qutip\qutip\qobj.py", line 455, in __mul__
    raise TypeError("Incompatible Qobj shapes")
TypeError: Incompatible Qobj shapes

----------------------------------------------------------------------
```

**Comment by cgranade** [comment]
This PR should now be caught up with #390, which should fix the problem with the new unit tests.

**Comment by cgranade** [comment]
This now passes checks, so I'm happy to merge.

**Comment by jrjohansson** [comment]
+1

**Comment by cgranade** [comment]
Seeing whether anything breaks with the other PRs merged in. If it's still good, I'll merge this too and then focus on #389.

**Pull request merged**
