### PR TITLE
Fix for iterative lu solve atol keyword issues

### LINKED ISSUE #862: Tests failing (possibly) due to scipy Deprecation in power-gmres solver
I can't quite figure out if this is simply due to the DeprecationWarnings or something else but all tests are failing due to `atol` not being set for the gmres solver. I will try to set `atol` and check if the tests pass.

Error log: https://api.travis-ci.org/v3/job/379109482/log.txt.
```
scipy/sparse/linalg/isolve/iterative.py:2: DeprecationWarning: scipy.sparse.linalg.bicgstab called without specifying `atol`. The default value will be changed in a future release. For compatibility, specify a value for `atol` explicitly, e.g., ``bicgstab(..., atol=0)``, or to retain the old behavior ``bicgstab(..., atol='legacy')``


```

```
..................................................
======================================================================
ERROR: Steady state: Thermal qubit - power-gmres solver
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/shahnawaz/miniconda3/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/shahnawaz/dev/qutip/qutip/tests/test_steadystate.py", line 145, in test_qubit_power_gmres
    rho_ss = steadystate(H, c_op_list, method='power-gmres')
  File "/Users/shahnawaz/dev/qutip/qutip/steadystate.py", line 298, in steadystate
    return _steadystate_power(A, ss_args)
  File "/Users/shahnawaz/dev/qutip/qutip/steadystate.py", line 863, in _steadystate_power
    v = v / la.norm(v, np.inf)
  File "/Users/shahnawaz/miniconda3/lib/python3.6/site-packages/scipy/linalg/misc.py", line 137, in norm
    a = np.asarray_chkfinite(a)
  File "/Users/shahnawaz/miniconda3/lib/python3.6/site-packages/numpy/lib/function_base.py", line 1233, in asarray_chkfinite
    "array must not contain infs or NaNs")
ValueError: array must not contain infs or NaNs

----------------------------------------------------------------------
Ran 561 tests in 576.175s

FAILED (SKIP=19, errors=1)
```

### PR DESCRIPTION
**Pull request by ajgpitch**
Hopefully this will fix #862 
Unfortunately 'legacy' did not behave as scipy 0.x. Some tests still failed. I had to add facility to set much higher tol on the gmres method.
The missing kwarg is handled. So should work for scipy < 1.1

### CODE REVIEW

**Comment by ajgpitch** [comment]
I just tidied up the branch with a rebase.
Tests are all passing except in the NOMKL build - this is not related, see #871 

I think this should be merged. @nonhermitian @sahmed95 please could someone check and merge if you agree

**Comment by ajgpitch** [comment]
Still only the sp_eigs test failing in NOMKL build

**Comment by sahmed95** [comment]
I made some pep8 fixes since we are revisiting this code after a long time. Is it okay to merge this even when the MKL build fails? Or should this test be disabled on MKL and then we merge this PR?

**Comment by ajgpitch** [comment]
The anaconda people have said they have / will fix the scipy openblas package in the next few days, so I think we can wait.
However, I see there were hundreds of new failures in all the py3 latest tests. I will set them of again, see what happens

**Comment by ajgpitch** [comment]
I'm merging this now. All tests are at least now running. The ones related to this are passing.
The errors #872 are not related to this

**Pull request merged**
