### PR TITLE
ENH: Enforce Qobj data is fast_csr

### PR DESCRIPTION
**Pull request by nonhermitian**
This pull implements a safety check where the Qobj data class is validated as fast_csr_matrix type everytime the Q.data attribute is set.  This guarantees that the Qobj's have the correct data type.  This was not always true previously.

In addition, many items are fixed so that the above rule passes.  Finally, we no longer need the tests that check for Qobj csr_matrix type.  This is now strictly enforced.

### CODE REVIEW

**Comment by ajgpitch** [comment]
Is this merge ready? I am looking to make the 4.0.2 release

**Comment by nonhermitian** [comment]
Should be

**Comment by ajgpitch** [comment]
I see you did a lot of work here!

**Comment by nonhermitian** [comment]
Just something to do while jet lagged.

**Comment by ajgpitch** [comment]
I am going to give it a final test on Windows, then build into 4.0.2

**Comment by sahmed95** [comment]
Hi, I am getting this error on the current master. I guess this will be solved once this PR is merged ?

```
air:tests shahnawaz$ nosetests test_sparse.py
E
======================================================================
ERROR: Failure: ImportError (No module named 'qutip.cy.spconvert')
```

**Comment by sahmed95** [comment]
Never mind, I needed a re build.

**Pull request merged**
