### PR TITLE
V4.5.1v4

### PR DESCRIPTION
**Pull request by nathanshammah**
**Description**
Add some `skipif` to bypass tests that were failing (segmentation faults) during the local testing of `qutip.testing.run()` that was failing in the zip version of #1241. I am on Mac with generic BLAS and no MKL. 
I have been installing it on a fresh conda environment with
```
pip install -e .[development]
```
which I think is better than 
```
python setup.py develop
```
and by the way maybe this is something that can be updated in the readme and docs.
 
My qutip.about reads:
```
QuTiP Version:      4.5.1
Numpy Version:      1.15.4
Scipy Version:      1.4.1
Cython Version:     0.29.8
Matplotlib Version: 3.1.2
Python Version:     3.7.3
Number of CPUs:     2
BLAS Info:          Generic
OPENMP Installed:   False
INTEL MKL Ext:      False
Platform Info:      Darwin (x86_64)
Installation path:  /Users/nathanshammah/github/qutip-4.5.1/qutip
```
This PR could be included in the 4.5.1 version @Ericgig. 

**Related issues or PRs**
This PR is related to  #1241.

**Changelog**
Add `skipif`in `pytest` on Mac with generic BLAS, avoiding segmentation fault during `qutip.testing.run()`.

### CODE REVIEW

**Comment by nathanshammah** [comment]
I'm not sure of all these changes. I just added the skipifs, copying the .zip file from Eric email.

**Comment by Ericgig** [comment]
There is a lot more changes than the skipif... What are those other change?

**Comment by Ericgig** [comment]
Nathan, you are pushing to the master branch, not qutip-4.5.1.
This would probably undo some commit to master that are not included in 4.5.1.

**Comment by Ericgig** [comment]
@nathanshammah could you remake it but branching off _qutip-4.5.1_ and merging to the same. Do not pull master, 4.5.1 does not have all commits of the main branch.

**Pull request closed without merging**
