### PR TITLE
Sysconfig fix

### PR DESCRIPTION
**Pull request by nonhermitian**
Simpel fix for depreciation warning is sysconfig used to remove old cython temp files.

### CODE REVIEW

**Comment by nonhermitian** [comment]
@cgranade and @ajgpitch : #393 should be merged before this and other pulls are verified with Travis.

**Comment by cgranade** [comment]
Sounds good, I'll review #393 this afternoon, then.

**Comment by cgranade** [comment]
With #393 now in, can you update your branch from master? Thanks!

**Comment by nonhermitian** [comment]
The sysconfig docs are a little terse on the subject, but the tests show that the depreciation fix is not compatible with 2.7.

**Comment by nonhermitian** [comment]
If there are no objections, I will merge this soon.

**Comment by cgranade** [comment]
Sounds good, +1.

**Pull request merged**
