### PR TITLE
BUG: pyx still in package data

### PR DESCRIPTION
**Pull request by nonhermitian**
Looks like the pyx files are back.  Probably due to a Pull that was committed but not up to date with master.

### CODE REVIEW

**Comment by ajgpitch** [comment]
No, it was deliberate. I added these in as part of the 4.0 release. They need to be distributed with the pip installer, otherwise it cannot build. At least that is why I added them in.

**Comment by nonhermitian** [comment]
Then I guess we would need to add the Cy_grape one in the control folder back.  I can do that here.  Should be fine as I think moving the pyximport call to the end of __init__ fixed the double cythonize.

**Comment by ajgpitch** [comment]
Yes, pretty sure the double cythonize was fixed by your moving the pyximport call to the end of init fix.
Not sure the cy grape is used by anyone, but probably best to put it back for now.

**Comment by ajgpitch** [comment]
I think we will need the `pyx` in the `cy` folder as well.

**Comment by nonhermitian** [comment]
You are indeed correct.

**Pull request merged**
