### PR TITLE
Fix setup.py for use from external requirements.txt

### PR DESCRIPTION
**Pull request by cgranade**
As raised in #426, QuTiP currently does not install correctly if listed in the requirements.txt for an external project unless the target environment already has numpy installed. This is due to the use of ``numpy.distutils`` in the current ``setup.py``, such that this PR attempts to solve the issue by falling back to setuptools and then distutils when numpy is missing.

### CODE REVIEW

**Comment by cgranade** [comment]
Testing locally in a conda environment without NumPy, this seems to work. In particular, I tested with the following commands:

```bash
$ conda create -n nonp python=2.7
$ source activate nonp
$ pip install git+https://github.com/cgranade/qutip.git@fix-setup-numpy#egg=QuTiP
```

**Comment by cgranade** [comment]
As a test, I've used this PR from the RTD build for [qinfer/python-qinfer](https://github.com/QInfer/python-qinfer), since the RTD virtualenv is by default rather restrictive. The modified setup.py works for that build process, which I think is a fairly good sign.

**Comment by cgranade** [comment]
After more examination, it appears as though ``qutip/cy/setup.py`` breaks the fix introduced by this PR if Cython is not installed before QuTiP. I'll investigate, but I'd like to get ``pip install`` working even from very minimal environments.

**Comment by cgranade** [comment]
My current understanding is that if NumPy is installed but not Cython, then when ``egg-info`` is called, NumPy distutils will happily follow ``add_subpackage`` to pull in ``qutip/cy/setup.py``, then choke on the missing Cython dependency. On the other hand, if both are missing, the new fallbacks introduced in this PR will be tripped, such that the ``add_subpackage`` call will not happen, and ``qutip/cy/setup.py`` will not get called. I'll readily admit that NumPy but not Cython is an edge case, but it's one that we can probably deal with by trying to import Cython at the top and letting the ``ImportError`` branch us onto the fallback path. Thoughts?

**Comment by cgranade** [comment]
The latest attempt seems to correctly generate ``egg_info`` if NumPy is missing, if NumPy is present by not Cython, or if both are present. That should make it much easier to list QuTiP as an external dependency in ``requirements.txt``, as  our``setup.py`` should no longer assume a particular install order. If the latest CI passes, I'll add the review merge ready label.

**Comment by ajgpitch** [comment]
I don't claim to understand the technical details, but this seems like a very good idea. And would seem to be ready to merge

**Comment by cgranade** [comment]
Cool, merging now, then. Thanks!

**Pull request merged**
