### PR TITLE
removed usingned int in prange

### PR DESCRIPTION
**Pull request by Ericgig**
Removed the unsigned int in the openmp loop mentioned in #955

### CODE REVIEW

**Comment by ajgpitch** [comment]
closes #955

**Comment by ajgpitch** [comment]
Thanks @Ericgig 
I will be trying out the Windows build stuff either later or tomorrow. I will test this then.

**Comment by Siddhant9868** [comment]
Hi
I have a Windows machine, I can also help in checking for the build.

**Comment by nathanshammah** [comment]
Yes please.

Il giorno mar 26 feb 2019 alle ore 21:18 SIDDHANT SINGH <
notifications@github.com> ha scritto:

**Pull request merged**
