### PR TITLE
Qobjevo solvers

### PR DESCRIPTION
**Pull request by Ericgig**
Rewrote sesolve, mesolve and mcsolve to use QobjEvo.
Compatible with previous version, solvers' test pass without modification.

Feature/imporvement:
- state can be obtain as an argument as a vector or Qobj.
- expectation values also can be arguments.
- The system is saved in a object to be reuse.
- mcsolve is fully class based. (but the use as object is not documented)
- s/mesolve follow a similar pattern to be easily made to class.
- Experimental: diagonalized mcsolve.

### CODE REVIEW

**Comment by Ericgig** [comment]
Matching notebook PR: https://github.com/qutip/qutip-notebooks/pull/71

**Comment by nathanshammah** [comment]
Somehow, rerunning the Jupyter Notebook or python from bash after reactivating the conda environment gives an error when importing qutip. 
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-69863217b56d> in <module>
      1 import numpy as np
----> 2 from qutip import *

~/github/qutip/qutip/__init__.py in <module>
    205 from qutip.mesolve import *
    206 from qutip.sesolve import *
--> 207 from qutip.mcsolve import *
    208 from qutip.stochastic import *
    209 from qutip.essolve import *

~/github/qutip/qutip/mcsolve.py in <module>
     46 from qutip.qobjevo import QobjEvo
     47 from qutip.parallel import parfor, parallel_map, serial_map
---> 48 from qutip.cy.mcsolve import CyMcOde, CyMcOdeDiag
     49 # cy_mc_run_ode = None
     50 from qutip.sesolve import sesolve

~/github/qutip/qutip/cy/cqobjevo_factor.pxd in init qutip.cy.mcsolve()

ValueError: qutip.cy.cqobjevo_factor.CoeffFunc size changed, may indicate binary incompatibility. Expected 40 from C header, got 32 from PyObject

```

**Comment by nathanshammah** [comment]
I re-launched the Travis tests on all platforms. They pass for all besides Mac OS (similar error as for other PR). With `python setup.py install`, with `install` instead of `develop`, things seem to work. What it is unclear to me is why it reads that the QuTiP Version is `4.4.0.dev0+1a639d7a`, when I could not find this hash in here (or maybe I am confused).

Now, after some tries with install and develop, I am on that version of qutip-dev. 

To begin with, I am running the contents of the [development notebooks](https://github.com/qutip/qutip-notebooks/tree/master/development).

Some comments below are relevant to the 

* `development-qobjevo.ipynb`: Runs fine. 
* `development-qobjevo-adv.ipynb`: Runs fine. 
* `development-qobjevo-timing.ipynb`: Runs fine.

* The notebook [development-qobjevo.ipynb](https://github.com/qutip/qutip-notebooks/blob/master/development/development-qobjevo.ipynb) could be re-adapted to be among other tutorials, with some title like "Time-dependent `Qobj` with `QobjEvo`". There could be much more commentary of the basics of `QobjEvo`. Some could be copy-pasted from the introductory comment in `qobjevo.py`. You are the best person to explain, with basic examples, of increasing complexity, what QobjEvo can do. Possibly taking a known physics problem, e.g., the damped harmonic oscillator with `mesolve`, could help the user.   

* In [development-qobjevo.ipynb](https://github.com/qutip/qutip-notebooks/blob/master/development/development-qobjevo.ipynb), block 22 has the first check set to False, but this is both in the notebook I run locally and in the one online. So probably that's the expected behaviour. 

 In [development-qobjevo-adv.ipynb](https://github.com/qutip/qutip-notebooks/blob/master/development/development-qobjevo-adv.ipynb), block 20 has a comment that is an unfinished sentence. In general, I think that examples could be much more descriptive, with comments, about the tests that are being performed. 


* I wonder whether `qobjevo_codegen.py` should stay there. It stands out from all other modules, also because in the other cases the title are self-explanatory. 
Regarding this comment:
```
Function to build cython code from str, compile and import it.
Used by cQobjEvo.
cy/codegen.py does the same thing for specific solver
```
could then this file by moved to `qutip/cy/`?

* In [development-qobjevo-timing.ipynb](https://github.com/qutip/qutip-notebooks/blob/master/development/development-qobjevo-timing.ipynb), block 24 online has a printed error `TypeError: __call__() got an unexpected keyword argument 'args'`, yet on my machine runs fine, it can be replaced. I opened a PR, also running the last blocks and qutip.about(), https://github.com/qutip/qutip-notebooks/pull/72. 

* In [development-qobjevo-timing.ipynb](https://github.com/qutip/qutip-notebooks/blob/master/development/development-qobjevo-timing.ipynb), `Time for cte` could be more explanatory. Similarly elsewhere.

* I wonder whether instead `QobjEvo`, `Qobjt` could be even more intuitive for the user.

* I would really encourage you to write one notebook (or more), about the new functionalities of the stochastic solvers, as well as the old methods. This could be the to-go resource, beyond documentation, to understand how these stochastic solvers are now expanded and coherently defined. It does not need to be a lot of work, it can copy a lot of stuff from the development notebooks. It would be fundamental to have the solvers' master equations written down, explaining for each solver what each term is, e.g., the jump operator. Also, in `development-smesolve-tests`, the equations are already there for example. Block 23 is beautiful, and it could be reproduced in the tutorial. 

* Similarly, a user guide entry would really enhance the adoption of these solvers. At a later stage, some more refined example applications could be provided.

* Review is still ongoing, I will provide comments on the .py files and other solvers files. Help from other developers is welcome as these are massive changes.

**Comment by Ericgig** [comment]
@nathanshammah 
I split this PR in 2 with #990 being the not solver part of this PR.
(#990 is halfway between this and master.)
I will see if I can do another one with just mcsolve (between this and the new PR).

**Comment by nathanshammah** [comment]
We have some conflicts in mcsolve.py. 

Some of them relate to ` _exp`. The last two are very long and hard to understand. Any help is welcome.

**Comment by Ericgig** [comment]
I will check this today.

**Comment by nathanshammah** [comment]
Travis on the eventually merged PR (not on the pushed one) is for the first time in a long time not failing on Mac.

**Comment by nathanshammah** [comment]
Also, never before, that I can recall, the tests were running on both the push and pull request. Hope this is working but not just by chance. Congrats @Ericgig on this too.

**Pull request merged**
