### PR TITLE
Clean up pulse optimization sparse solving support.

### LINKED ISSUE #1617: Issue with optimize_pulse_unitary for large sparse matrices
I am using GRAPE to identify optimal pulse sequences to produce a desired unitary, and am running into an error when I use optimize_pulse_unitary for sparse matrices of size 1296x1296 and larger.  

For example, the following code works for N=2 but fails for N=>3:

```python
import numpy as np
from qutip import *
from scipy.sparse import csr_matrix
import qutip.logging_utils as logging
logger = logging.get_logger()
#Set this to None or logging.WARN for 'quiet' execution
log_level = logging.INFO
#QuTiP control modules
import qutip.control.pulseoptim as cpo
import math

# Set parameters
chi  = 2.2 * 2 * np.pi  # coupling strength
N = 3             # number of cavity states
n_ts = 21 # number of discrete time steps
evo_time = 4.      # Length of time
fid_err_targ = 1e-10 # Target fidelity error
max_iter = 0 # # Maximum iterations for the optimization algorithm
max_wall_time = 0 # Maximum (elapsed) time
min_grad = 1e-20 # Minimum gradient
p_type = 'SINE' # pulse type (RND|ZERO|LIN|SINE|SQUARE|SAW|TRIANGLE)
f_ext = "pulsedata.txt" # output file

# Set operators and Hamiltonians

# operators
a  = tensor(destroy(N), qeye(N), qeye(N), qeye(N), qeye(2), qeye(2), qeye(2), qeye(2))
b = tensor(qeye(N), destroy(N), qeye(N), qeye(N), qeye(2), qeye(2), qeye(2), qeye(2))
c  = tensor(qeye(N), qeye(N), destroy(N), qeye(N), qeye(2), qeye(2), qeye(2), qeye(2))
d = tensor(qeye(N), qeye(N), qeye(N),  destroy(N), qeye(2), qeye(2), qeye(2), qeye(2))
sm = tensor(qeye(N), qeye(N), qeye(N), qeye(N), destroy(2), qeye(2), qeye(2), qeye(2))
zm = tensor(qeye(N), qeye(N), qeye(N), qeye(N), qeye(2), destroy(2), qeye(2), qeye(2))
tm = tensor(qeye(N), qeye(N), qeye(N), qeye(N), qeye(2), qeye(2), destroy(2), qeye(2))
qm = tensor(qeye(N), qeye(N), qeye(N), qeye(N), qeye(2), qeye(2), qeye(2), destroy(2))
P_se = tensor(qeye(N), qeye(N), qeye(N), qeye(N), basis(2, 1) * basis(2, 1).dag(), qeye(2), qeye(2), qeye(2))
P_ze = tensor(qeye(N), qeye(N), qeye(N), qeye(N), qeye(2), basis(2, 1) * basis(2, 1).dag(), qeye(2), qeye(2))
P_te = tensor(qeye(N), qeye(N), qeye(N), qeye(N), qeye(2), qeye(2), basis(2, 1) * basis(2, 1).dag(), qeye(2))
P_qe = tensor(qeye(N), qeye(N), qeye(N), qeye(N), qeye(2), qeye(2), qeye(2), basis(2, 1) * basis(2, 1).dag())

# Hamiltonians
drift = chi * (a.dag() * a * P_se) + chi * (b.dag() * b * P_ze) + chi * (c.dag() * c * P_te) + chi * (d.dag() * d * P_qe)

row = np.array([1,1,2,2,3,3,3,3,4,4,4,4,5,5,6,6])
column = np.array([3,4,3,4,1,2,5,6,1,2,5,6,3,4,3,4])
data = np.array([-1,1,-1,-1,-1,-1,-1,-1,1,-1,-1,1,-1,-1,-1,1])

mapped=csr_matrix((data,(row,column)),shape=(N**4*2*2*2*2,N**4*2*2*2*2))
mapped=Qobj(mapped)

n_ctrls=4 # Controls
ctrls = [sm.dag()*a+sm*a.dag()+sm.dag()*b+sm*b.dag()+zm.dag()*b+zm*b.dag()+zm.dag()*c+zm*c.dag()+tm.dag()*c+tm*c.dag()+tm.dag()*d+tm*d.dag()+qm.dag()*d+qm*d.dag()+qm.dag()*a+qm*a.dag(),1j*(sm.dag()*a-sm*a.dag())+1j*(sm.dag()*b-sm*b.dag())+1j*(zm.dag()*b-zm*b.dag())+1j*(zm.dag()*c-zm*c.dag())+1j*(tm.dag()*c-tm*c.dag())+1j*(tm.dag()*d-tm*d.dag())+1j*(qm.dag()*d-qm*d.dag())+1j*(qm.dag()*a-qm*a.dag()),sm+sm.dag()+zm+zm.dag()+tm+tm.dag()+qm+qm.dag(), 1j*(sm-sm.dag())+1j*(zm-zm.dag())+1j*(tm-tm.dag())+1j*(qm-qm.dag())]

# Set optimization parameters
U_0=tensor(qeye(N), qeye(N), qeye(N), qeye(N), qeye(2), qeye(2), qeye(2), qeye(2)) # Initial gate
U_targ=mapped # Target gates

# Run the optimization

result = cpo.optimize_pulse_unitary(drift, ctrls, U_0, U_targ, n_ts, evo_time, fid_err_targ=fid_err_targ, min_grad=min_grad, max_iter=max_iter, max_wall_time=max_wall_time, out_file_ext=f_ext, init_pulse_type=p_type, log_level=log_level,gen_stats=True,dyn_params=dict(sparse_eigen_decomp=True))

```
For N=>3, instead of getting a printout of the optimized controls, I receive the following terminal output error:
```
Traceback (most recent call last):
  File "MinimalErrorExample.py", line 59, in <module>
    result = cpo.optimize_pulse_unitary(drift, ctrls, U_0, U_targ, n_ts, evo_time, fid_err_targ=fid_err_targ, min_grad=min_grad, max_iter=max_iter, max_wall_time=max_wall_time, out_file_ext=f_ext, init_pulse_type=p_type, log_level=log_level,gen_stats=True,dyn_params=dict(sparse_eigen_decomp=True))
  File "/Users/msoley/opt/anaconda3/lib/python3.7/site-packages/qutip/control/pulseoptim.py", line 829, in optimize_pulse_unitary
    gen_stats=gen_stats)
  File "/Users/msoley/opt/anaconda3/lib/python3.7/site-packages/qutip/control/pulseoptim.py", line 510, in optimize_pulse
    result = optim.run_optimization()
  File "/Users/msoley/opt/anaconda3/lib/python3.7/site-packages/qutip/control/optimizer.py", line 970, in run_optimization
    result = self._create_result()
  File "/Users/msoley/opt/anaconda3/lib/python3.7/site-packages/qutip/control/optimizer.py", line 375, in _create_result
    result.initial_fid_err = self.dynamics.fid_computer.get_fid_err()
  File "/Users/msoley/opt/anaconda3/lib/python3.7/site-packages/qutip/control/fidcomp.py", line 448, in get_fid_err
    return np.abs(1 - self.get_fidelity())
  File "/Users/msoley/opt/anaconda3/lib/python3.7/site-packages/qutip/control/fidcomp.py", line 458, in get_fidelity
    self.fid_norm_func(self.get_fidelity_prenorm())
  File "/Users/msoley/opt/anaconda3/lib/python3.7/site-packages/qutip/control/fidcomp.py", line 474, in get_fidelity_prenorm
    dyn.compute_evolution()
  File "/Users/msoley/opt/anaconda3/lib/python3.7/site-packages/qutip/control/dynamics.py", line 1421, in compute_evolution
    self.tslot_computer.recompute_evolution()
  File "/Users/msoley/opt/anaconda3/lib/python3.7/site-packages/qutip/control/tslotcomp.py", line 299, in recompute_evolution
    prop_comp._compute_prop_grad(k, j)
  File "/Users/msoley/opt/anaconda3/lib/python3.7/site-packages/qutip/control/propcomp.py", line 272, in _compute_prop_grad
    dyn._ensure_decomp_curr(k)
  File "/Users/msoley/opt/anaconda3/lib/python3.7/site-packages/qutip/control/dynamics.py", line 1437, in _ensure_decomp_curr
    self._spectral_decomp(k)
  File "/Users/msoley/opt/anaconda3/lib/python3.7/site-packages/qutip/control/dynamics.py", line 1654, in _spectral_decomp
    dims=self.dyn_dims)
  File "/Users/msoley/opt/anaconda3/lib/python3.7/site-packages/qutip/qobj.py", line 292, in __init__
    _tmp = sp.csr_matrix(inpt, dtype=complex, copy=do_copy)
  File "/Users/msoley/opt/anaconda3/lib/python3.7/site-packages/scipy/sparse/compressed.py", line 88, in __init__
    self._set_self(self.__class__(coo_matrix(arg1, dtype=dtype)))
  File "/Users/msoley/opt/anaconda3/lib/python3.7/site-packages/scipy/sparse/coo.py", line 191, in __init__
    self.row, self.col = M.nonzero()
  File "/Users/msoley/opt/anaconda3/lib/python3.7/site-packages/scipy/sparse/base.py", line 287, in __bool__
    raise ValueError("The truth value of an array with more than one "
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all().

```

I am using the following QuTiP environment:
QuTiP Version:      4.4.1
Numpy Version:      1.21.0
Scipy Version:      1.4.1
Cython Version:     0.29.15
Matplotlib Version: 3.4.2
Python Version:     3.7.6
Number of CPUs:     2
BLAS Info:          OPENBLAS
OPENMP Installed:   False
INTEL MKL Ext:      False
Platform Info:      Darwin (x86_64)

Thank you for your help.

### PR DESCRIPTION
**Pull request by hodgestar**
Currently qutip.control.optimize_pulse supports four formats for `oper_dtype` (i.e. its internal representation of propagators and intermediate states). The four formats and their statuses before this PR are described below:

- `numpy.ndarray`: Working.
- `Qobj`: Working, except that some dimensions were lost in Qobj construction and using sparse eigenvector decomposition was broken.
- `scipy.sparse.csr_matrix`: Broken. There was an undefined variable referenced in the code to construct the propagators. Many code paths had no explicit support for them and assumed they worked the same as ndarrays in cases where they didn't.
- `anything matrix-like`: Broken for the same reasons as `csr_matrix` above.

This PR removes support for last two oper_dtypes and fixes the `Qobj` one, leaving the situation as follows:

- `numpy.ndarray`: Working.
- `Qobj`: Working.
- `scipy.sparse.csr_matrix`: No longer supported.
- `anything matrix-like`: No longer supported.

Note that `Qobj` uses sparse matrices internally, so CSR matrix support is still available via the `Qobj` oper_dtype.

In QuTiP v5, only `Qobj` support will be retained since `Qobj` will support both sparse and dense representations via the data layer.

**Related issues or PRs**
* Fixes #1617

**Changelog**
Fix qutip.control.optimize_pulse support for sparse eigenvector decomposition with the Qobj oper_dtype (the Qobj oper_dtype is the default for large systems).
Remove qutip.control.optimize_pulse support for scipy.sparse.csr_matrix and generic ndarray-like matrices. Support for these was non-functional.

### CODE REVIEW

**Comment by hodgestar** [comment]
@Ericgig @ajgpitch These are quite big changes, so I'd appreciate thoughts and happy to implement a completely different fix if someone prefers.

**Comment by Ericgig** [comment]
Removing broken code is the good approach, there is no point in trying to fix it now.
Hopefully we will have time to do more aggressive changes for v5.
We have qutip/qutip-control and we may be moving it there, @ajgpitch would know more about the plan.

**Comment by hodgestar** [comment]
@Ericgig I'm not sure when @ajgpitch will get a chance to look at this. Are you happy for me to merge it?

**Review by Ericgig — APPROVED** [review]
I am happy with it, but we should wait for @ajgpitch since i am not fresh with all parts of control.

**Comment by ajgpitch** [comment]
Looks good to me. This is a good idea. Thanks @hodgestar for sorting this.
Please go ahead and merge

**Pull request merged**
