### PR TITLE
matrix_histogram_complex() colorbar pad to 0.05

### PR DESCRIPTION
**Pull request by SJUW**
**Description**
Increase missing colorbar padding for matrix_histogram_complex() from 0 to 0.05.

### CODE REVIEW

**Comment by Ericgig** [comment]
Thank you @SJUW for the PR.
We have a GSoC reworking our visualization functions this summer.
@tamakoshi2001 would you be up to review this?

**Comment by tamakoshi2001** [comment]
@Ericgig Sure!

**Comment by tamakoshi2001** [comment]
@SJUW Hi. Can you show me a plot? I want to see that your change is better.

**Comment by SJUW** [comment]
Thanks all, I am new to this and I apologise for the extra help required.

Here is the plot.

Just FYI, the function "matrix_histogram" is much more robust than
"matrix_histogram_complex", and has cbar_pad as an option. It may be better
in the long run to base the complex version on the "matrix_histogram"
function.
[image: image.png]

**Comment by SJUW** [comment]
image

**Comment by tamakoshi2001** [comment]
@SJUW Thank you! It looks better.
Yes. We plan to merge matrix_histogram and matrix_histogram_complex.

Can you add a towncrier?  The way is here;
https://qutip.org/docs/latest/development/contributing.html

**Comment by tamakoshi2001** [comment]
@SJUW Thanks!

**Comment by tamakoshi2001** [comment]
@Ericgig Hi. His work is fine for me.

**Review by Ericgig — APPROVED** [review]

**Pull request merged**
