### PR TITLE
Don't print msg when mesolve falls back to sesolve

### PR DESCRIPTION
**Pull request by goerz**
This addresses #1047 by removing the print statement

### CODE REVIEW

**Comment by nathanshammah** [comment]
It says the PR is still a WIP and cannot be merge now: just checking if it was set on purpose like this or if it's ready.

**Comment by nathanshammah** [comment]
I've never seen a [draft on github](https://github.blog/2019-02-14-introducing-draft-pull-requests), looks interesting for @boxili @quantshah @ajgpitch.

**Comment by goerz** [comment]
Sorry.. got a little distracted, and wanted to check the contributing guidelines on what branch to make the pull request against. Currently it’s master.  Is that ok? If yes, I’ll undraft it.

Draft PRs are pretty new, and a very nice way to kick off the Continuous Integration. Like in this case, I wanted to check if any of the tests involve that message. As they don’t, this actually is ready to go.

**Comment by quantshah** [comment]
Looks cool, you can make the PR against the master branch. We do not have a
dev branch.

**Pull request merged**
