### PR TITLE
Fix logging

### PR DESCRIPTION
**Pull request by cgranade**
This should at least partially address #377, as it seems that ``from __future__ import absolute_import`` isn't causing the built-in ``logging`` to appear in preference to ``qutip.logging`` on Windows 8. Given the hassles of calling both ``logging``, the idea behind this PR is to just rename and avoid conflicts that way.

### CODE REVIEW

**Comment by ajgpitch** [comment]
I didn't realise that was causing a problem too. Seems like a good idea generally to try and avoid conflicts with built in names where possible.

**Comment by jrjohansson** [comment]
Looks like a reasonable and practical solution to me.

Regarding the logging system in qutip, I think that it also would be worth making some changes to how it is used. As it is now, qutip does not really use the Python logging system in the way it is intended. The best way to use it would be to have each submodule that use logging use something like:

    import logging
    logger = logging.getLogger(__name__)

and then log at different levels using the logger instance, for example

    logger.debug("debug msg")

or

    logger.warning("warning msg")

etc.

The only utilities that would be required in qutip.logging_utils would then be to optionally create a stream or file handler for the "qutip" package or any of its submodules. This would allow selectively tuning logging for different submodules if requried, and there we not be any need for checking if qutip.settings.debug is set or to set logging levels explicitly in any submodules (as currently in done in the steadystate module for example).

Not saying that is should be done in this PR, but would probably be worth sorting this out at some point.

**Comment by ajgpitch** [comment]
I really can't see how the changes here could be causing the Travis errors. @cgranade any ideas?

**Comment by cgranade** [comment]
I looked at the failures and they seem to be in parts that are completely disconnected from logging. I have no idea why they aren't also in the main branch, but I'll investigate.

Anyway, I agree with you, @jrjohansson, that the current implementation is not in keeping with the design of Python's logging package. At the time, it was a bit of a hack to try and make it fit as well as possible, but I think in retrospect that may have been misguided. Do you think the refactoring to more appropriately use Python logging would be a good 3.2.0 feature, or would you suggest that for ≥ 3.3? Thanks!

**Comment by ajgpitch** [comment]
I notice that I am also getting the same error on the travis build in the latest branch on my fork. An error that I do not get on my local machine. I will try a fresh conda env later and see if I can reproduce it.

**Comment by ajgpitch** [comment]
The Travis error occurred because the latest numpy v1.10 did not allow some implicit cast from object to complex. I have fixed this in #380 
@cgranade  I guess we can merge that, then you can rebase from master (or similar process)

**Comment by cgranade** [comment]
That makes sense, then, though I'm surprised that the version of numpy used by the Travis CI build suddenly changed. I'll merge in your fix on #380, at which point this really should work.

**Comment by ajgpitch** [comment]
The Travis build seems to create a new conda env each time it runs the test. Consequently it downloads and installs the latest [conda] numpy, scipy etc. I tried creating a fresh conda env yesterday and found that the numpy version was higher than my qutip dev env, which I created a few months ago.

**Comment by ajgpitch** [comment]
I am merging this now because I need to rebase my latest branch

**Pull request merged**
