### PR TITLE
BUG: Fix strange RHS file error on Win

### PR DESCRIPTION
**Pull request by nonhermitian**
This Pull attempts to fix the issues with Win not finding RHS functions when repeated time-dependent solvers are used in the tests.  I have also added some unit tests to verify that rhs_reuse still works.

### CODE REVIEW

**Comment by ajgpitch** [comment]
This seemed to fix the #728 issue. The specific test combination mentioned in that issue no longer fails.

**Comment by ajgpitch** [comment]
I ran the full tests on Windows 10. All passed except 1. Trace as follows:
```
======================================================================
FAIL: Monte-carlo: Collapse terms constant (str format)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Anaconda2\envs\q4_2-dev-py36\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "C:\Anaconda2\envs\q4_2-dev-py36\lib\site-packages\qutip-4.3.0.dev0+6915aee-py3.6-win-amd64.egg\qutip\tests\test_mcsolve.py", line 326, in test_MCSimpleConstStr
    assert_equal(avg_diff < mc_error, True)
  File "C:\Anaconda2\envs\q4_2-dev-py36\lib\site-packages\numpy\testing\utils.py", line 416, in assert_equal
    raise AssertionError(msg)
AssertionError:
Items are not equal:
 ACTUAL: False
 DESIRED: True
-------------------- >> begin captured stdout << ---------------------
10.0%. Run time:   8.27s. Est. time left: 00:00:01:14
20.0%. Run time:  10.17s. Est. time left: 00:00:00:40
30.0%. Run time:  12.19s. Est. time left: 00:00:00:28
40.0%. Run time:  14.11s. Est. time left: 00:00:00:21
50.0%. Run time:  16.05s. Est. time left: 00:00:00:16
60.0%. Run time:  18.03s. Est. time left: 00:00:00:12
70.0%. Run time:  19.99s. Est. time left: 00:00:00:08
80.0%. Run time:  21.94s. Est. time left: 00:00:00:05
90.0%. Run time:  23.94s. Est. time left: 00:00:00:02
100.0%. Run time:  25.87s. Est. time left: 00:00:00:00
Total run time:  25.99s

--------------------- >> end captured stdout << ----------------------

----------------------------------------------------------------------
Ran 488 tests in 2700.806s

FAILED (SKIP=9, failures=1)
>>>
```

**Comment by nonhermitian** [comment]
Those are subject to some error since the monte carlo method is random.  Try to run it again.

**Comment by ajgpitch** [comment]
Sorry for the delay - my Windows decided it needed an update, which took hours.
I ran the specific test `test_MCSimpleConstFunc` : OK
I ran all the interpolation followed by the all the mcsolve tests: OK
This would seem to resolve #728 
I would say this is ready to merge. Good work. Thank you @nonhermitian

**Comment by nonhermitian** [comment]
Alrighty.  Another bug squashed

**Pull request merged**
