### PR TITLE
Fix for #355

### PR DESCRIPTION
**Pull request by cgranade**

### CODE REVIEW

**Comment by ajgpitch** [comment]
Is this a necessary fix for #332? Should it be merged first?

**Comment by cgranade** [comment]
This PR should be independent of #332, as it fixes a visual error with plotting of channels as Pauli-basis superoperators.

**Comment by ajgpitch** [comment]
Yes, sorry, I meant to add that comment to #337

**Comment by ajgpitch** [comment]
I am happy with this and will merge if there are no other comments

**Comment by cgranade** [comment]
Wonderful, thank you!

**Pull request merged**
