### PR TITLE
Fix for #388

### PR DESCRIPTION
**Pull request by cgranade**
This PR starts work on fixing #388 by splitting out much of the logic handling lists of dims into a new module, ``dims_utils``, and providing a new function that converts between indices into ``Qobj.dims`` and tensor indices (as used by ``np.reshape``). While this PR is not yet done, I wanted to make a PR for the fixes early to solicit feedback.

### CODE REVIEW

**Comment by cgranade** [comment]
This PR now includes test cases that cover even quite strange tensor contractions. Hopefully these should be good canaries for pretty much all typical usages. That said, the new cases are failing for a surprising reason: ``Qobj.isket`` fails for "ragged" dims:

```python
In [1]: import qutip as qt

In [2]: import numpy as np

In [3]: qt.Qobj(np.arange(2 * 3 * 3 * 3 * 2 * 3).reshape((2 * 3 * 3, 2 * 3 * 3)), dims=[[[2], [3, 3]], [[3], [2, 3]]])
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-46359a4eb5bd> in <module>()
----> 1 qt.Qobj(np.arange(2 * 3 * 3 * 3 * 2 * 3).reshape((2 * 3 * 3, 2 * 3 * 3)), dims=[[[2], [3, 3]], [[3], [2, 3]]])

C:\Users\Chris\Dropbox\software-projects\qutip\qutip\qobj.pyc in __init__(self, inpt, dims, shape, type, isherm, fast, superrep)
    281             self.superrep = superrep
    282         else:
--> 283             if self.type == 'super' and self.superrep is None:
    284                 self.superrep = 'super'
    285

C:\Users\Chris\Dropbox\software-projects\qutip\qutip\qobj.pyc in type(self)
   1542             if self.isoper:
   1543                 self._type = 'oper'
-> 1544             elif self.isket:
   1545                 self._type = 'ket'
   1546             elif self.isbra:

C:\Users\Chris\Dropbox\software-projects\qutip\qutip\qobj.pyc in isket(self)
   1572     @property
   1573     def isket(self):
-> 1574         return (np.prod(self.dims[1]) == 1 and
   1575                 isinstance(self.dims[0], list) and
   1576                 isinstance(self.dims[0][0], (int, np.integer)))

C:\Anaconda\lib\site-packages\numpy\core\fromnumeric.pyc in prod(a, axis, dtype, out, keepdims)
   2347         except AttributeError:
   2348             return _methods._prod(a, axis=axis, dtype=dtype,
-> 2349                                 out=out, keepdims=keepdims)
   2350         return prod(axis=axis, dtype=dtype, out=out)
   2351     else:

C:\Anaconda\lib\site-packages\numpy\core\_methods.pyc in _prod(a, axis, dtype, out, keepdims)
     33
     34 def _prod(a, axis=None, dtype=None, out=None, keepdims=False):
---> 35     return umr_prod(a, axis, dtype, out, keepdims)
     36
     37 def _any(a, axis=None, dtype=None, out=None, keepdims=False):

TypeError: can't multiply sequence by non-int of type 'list'
```

Using the debugger, ``a`` in the last frame is ``[[3], [2, 3]]``, which chokes NumPy's ``product`` function. This may be worth splitting out into a new Issue, in fact, as it seems like that could be a problem for the kinds of superoperators that arise in the superchannel/supermap formalism.

**Comment by cgranade** [comment]
With the latest changes, ``Qobj.type`` now points at the new ``dims_utils.type_from_dims``, which consolidates the type-detection logic in one place and makes it more robust to ragged ``dims``. On Python 2 all tests of ``qobj``, ``tensor`` and ``dims_utils`` now pass locally, I'll try with Python 3 soon.

**Comment by jrjohansson** [comment]
Nice work! Thanks for starting the work on improving the dims concept. I think this has been long over due!

Personally I would probably call the module `dimensions.py` or simply `dims` instead of `dims_utils.py`, but please do as you wish.

**Comment by jrjohansson** [comment]
Sorry! ... re-opening the pr... didnt mean to close it, only to post a comment.

**Comment by cgranade** [comment]
Thanks, I'm glad you like! I like the suggestion of renaming to ``dimensions.py``, I'll go on and rename that before merging.

**Comment by cgranade** [comment]
This PR is now caught up with all recent progress, and has the new module renamed to ``dimensions.py``. If it works, I'll go on and merge it in so that I can start getting back to writing the new docs on ``tensor_contract`` (#385), as started this whole spree.

**Comment by cgranade** [comment]
Everything passes now, and the rename is included. Merging now.

**Pull request merged**
