### PR TITLE
PIQS module and updates

### PR DESCRIPTION
**Pull request by sahmed95**
Hi, we now have an arXiv entry for PIQS: https://arxiv.org/abs/1805.05129.

This version adds `pisolve` a custom solver for diagonal initial state and is updated to be synced with the latest version in the paper. We have also made some documentation in [piqs.readthedocs.io](piqs.readthedocs.io). Corresponding notebooks and docs will be added too.

@nathanshammah @ajgpitch

### CODE REVIEW

**Comment by ajgpitch** [comment]
@sahmed95 can you merge the new master into this.
I'll check it over when the tests are passing.
Thanks

**Comment by sahmed95** [comment]
This fails for python2.7 and it might also be related to older scipy version. I could not even install it locally in my python2.7 conda environment with scipy 0.15 as I get some compile errors for the `cy/brtools` module. One more reason to move to Python 3. @ajgpitch 

If you have seen this error before with a conda env clashing with the Python GIL, please let me know,
```
qutip/cy/brtools.pyx:98:51: Converting to Python object not allowed without gil
Traceback (most recent call last):
```
The conda environment is as follows:
```
# packages in environment at /Users/shahnawaz/miniconda3/envs/python2:
#
# Name                    Version                   Build  Channel
blas                      1.0                         mkl
ca-certificates           2018.4.16                     0    conda-forge
certifi                   2018.4.16                py27_0    conda-forge
cython                    0.28.3                   py27_0    conda-forge
intel-openmp              2018.0.3                      0
libgfortran               3.0.1                h93005f0_2
mkl                       2018.0.3                      1
ncurses                   5.9                          10    conda-forge
numpy                     1.9.3            py27hb3dd696_3
numpy-base                1.14.3           py27ha9ae307_2
openblas                  0.2.20                        8    conda-forge
openssl                   1.0.2o                        0    conda-forge
pip                       9.0.3                    py27_0    conda-forge
python                    2.7.15                        0    conda-forge
qutip                     4.3.0.dev0+2a849f2e           <pip>
readline                  7.0                           0    conda-forge
scipy                     0.15.1               np19py27_0
setuptools                39.2.0                   py27_0    conda-forge
sqlite                    3.20.1                        2    conda-forge
tk                        8.6.7                         0    conda-forge
wheel                     0.31.0                   py27_0    conda-forge
zlib                      1.2.11               h470a237_3    conda-forge
```

**Comment by sahmed95** [comment]
Ok, the issue seems to be rooted in Scipy's `block_diag` function which was fixed in 0.19.
https://github.com/scipy/scipy/issues/4908

I attempted to bump up the scipy and cython version and tested this locally. All tests pass now. I will try the same with conda.

```
QuTiP Version:      4.3.0.dev0+2ac36add
Numpy Version:      1.14.4
Scipy Version:      0.19.1
Cython Version:     0.28.3
Matplotlib Version: None
Python Version:     2.7.15
Number of CPUs:     4
BLAS Info:          OPENBLAS
OPENMP Installed:   False
INTEL MKL Ext:      False
Platform Info:      Darwin (x86_64)
Installation path:  /Users/shahnawaz/dev/qutip/qutip
```

**Comment by sahmed95** [comment]
Well, having a higher version of scipy and cython does not seem to fix it and we are plagued again by the `dnorm` issue. Attempting to run with the latest scipy (1.1) one last time. Otherwise, we should decide to include this after QuTiP drops python 2.7, or let it be merged as it is with a warning that python2 is not recommended for the `piqs` module. I cannot understand the error, as locally, all tests are passing.

**Comment by ajgpitch** [comment]
@sahmed95 You'll see I have raised #881 to solve the py3 test issues. You can merge that (into the master and this) if the tests pass.

On the py2 issues. I suggest you skip the tests (for Python 2.x) that are known to be failing. You can add something in the documentation that the PIQS module is only fully supported in Python >= 3.6.

While your doing the skipping change ... would be good if the PIQS / Dicke tests had some docstring prefix to show they relate to the same module.

**Comment by ajgpitch** [comment]
@sahmed95 I like everything you are doing with this PR. Looks good to me.
I assume that you have tested all the fancy docstrings with the documentation build.

I do think think it would be better if your test method docstrings started "PIQS: ". Is there a reason not to do this?

Otherwise I think it is merge ready

**Comment by sahmed95** [comment]
@ajgpitch Thanks for taking a look. I updated the docstring for the tests. The fancy docstrings are tested as the API docs are also up on piqs.readthedocs.io. We can also add a complete tutorial section with all the nice notebooks that @nathanshammah has compiled. I think this makes case for the long overdue 4.3 release? Should I open another thread for adding a warning for dropping python2 in QuTiP 5?

**Comment by ajgpitch** [comment]
I see, the docs look very nice indeed!
@sahmed95 Go ahead and merge this when the tests pass. Better if you do it, as you can tidy the commit message during the squash.

**Comment by ajgpitch** [comment]
I agree that 4.3 is long overdue. If you are happy to manage it that would be great. PIQS is a great headline for the release

**Pull request merged**
