### PR TITLE
WIP: nose to pytest: first step

### PR DESCRIPTION
**Pull request by BassemSafieldeen**
In .travis.yml: replaced nose installation lines with pytest installation lines.
Suggested in issue #958.

### CODE REVIEW

**Comment by quantshah** [comment]
Hi, thanks for the PR. Needless to say this isn't expected to be that easy and without hiccups. But hopefully it works out. I will have a better look and get back to this.

**Comment by nathanshammah** [comment]
@BassemSafieldeen thank you for addressing this enhancement. It would be nice to find out what's broken with pytest.

**Comment by BassemSafieldeen** [comment]
I think the problem is that ["pytest interprets the function name as a file name and it fails because the file does not exist." ](https://github.com/pytest-dev/pytest/issues/1110#issue-109663494). I am thinking about a fix.

**Comment by BassemSafieldeen** [comment]
Ok, that particular problem has been fixed. Now the build fails for 1 function: TestPulseOptim

**Comment by quantshah** [comment]
Hi, this is great. @agpitch, do you have any idea about the test? Looks like something related to optimal control and you could provide some insight. We can investigate the issue separately and fix this. Good job on the PR. Moving to PyTest will be great for us in the long run.

**Comment by nathanshammah** [comment]
- All builds fail a test regarding optimal control in `` fails with `AttributeError: 'TestPulseOptim' object has no attribute 'tmp_dirs'`.
- The MacOs build still exits with an error once it encounters `ptrace`.

**Comment by nathanshammah** [comment]
Cc @tehruhn.

**Comment by nathanshammah** [comment]
Thank you @BassemSafieldeen, this has been solved by #1131.

**Comment by BassemSafieldeen** [comment]
Happy to have helped!

**Pull request closed without merging**
