### PR TITLE
FIXED: Expm

### PR DESCRIPTION
**Pull request by nonhermitian**
Updated expm function.  Fixes bug in previous version.  Defaults to sparse=False as resulting matrix is almost always dense, and the algorithm runs about 10x faster.

### CODE REVIEW

**Comment by ajgpitch** [comment]
Very nice work Paul. 
I was kind of expecting to see use of the new is_diag that you implemented recently. Is it there and I have missed it?

**Comment by nonhermitian** [comment]
I was kind of expecting to have it there until I spaced it out.  Will add
tonight.

**Comment by ajgpitch** [comment]
Looks good to me

**Comment by nonhermitian** [comment]
Well, there are still some issues with the tests not passing. Probably due to the 1e-12 tol there.

**Comment by nonhermitian** [comment]
Ok, this is good now.  I tried to get away with using a lower Pade approx. but I guess 13th order is the way to go.

**Comment by cgranade** [comment]
Looks good to me as well, looks like a great enhancement!

**Comment by nonhermitian** [comment]
Merging this now then.

**Comment by ajgpitch** [comment]
Yes, good work.
I will see if I can follow your lead and create a sp_expm_frechet

**Comment by argriffing** [comment]
Please feel free to contribute improvements upstream! You can blame me for the scipy implementations of those functions, I'm just a postdoc who needed them for some computational biology calculations. Sorry if they are bad. Also they may be bit-rotting further due to the questionable 'LinearOperator' situation in scipy and the inconsistencies among the np.ndarray, np.matrix, scipy.sparse, and linear operator interfaces.

**Comment by nonhermitian** [comment]
No worries. Will add a pull tonight. Our previous implementation was also sketchy. Also wrote that as a postdoc before the SciPy version existed. Luckily, Expokit knows more than I do!

**Comment by nonhermitian** [comment]
Actually, with further testing it seems that the scipy method is better at larger sized matrices. Should probably stick with that one. The older qutip algorithm is closer to the matlab version per 3015b, and returns similar results. It seems the scipy one is a bit better behaved at larger sizes.

**Pull request merged**
