### PR TITLE
[DOC] Fixed a ducumentation typo.

### PR DESCRIPTION
**Pull request by AGaliciaMartinez**
**Description**
Fixed small typo in the documentation of `pdpsolve.py`

**Related issues or PRs**

**Changelog**
Fixed small typo in the documentation of `pdpsolve.py`

### CODE REVIEW

**Comment by AGaliciaMartinez** [comment]
I found a small typo in the documentation in `pdpsolve.py`. Is it ok to create a pull request for such a small change or should I have proceeded in a different way?

**Comment by hodgestar** [comment]
> I found a small typo in the documentation in `pdpsolve.py`. Is it ok to create a pull request for such a small change or should I have proceeded in a different way?

A pull request for small changes is great!

**Comment by hodgestar** [comment]
When you're ready, remove the draft status from the PR and we'll review.

**Comment by jakelishman** [comment]
Ah, this test failure reminds me I need to merge up the 4.6.0 release to `dev.major`.

Documentation fix is good, merging.

**Pull request merged**
