### PR TITLE
Fix for #425

### LINKED ISSUE #425: Qobj trunc_neg causing Travis errors
The tests for this are sometimes erroring in Travis
See test result for #424 
ERROR: Test Qobj: trunc_neg works for non-diagonal opers.

I saw a conversation about this somewhere, but can't find it now

### PR DESCRIPTION
**Pull request by cgranade**
This PR fixes how ``Qobj.trunc_neg_eigs(method='sgs')`` handles eigenvalues equal to 0, which should resolve #425.

### CODE REVIEW

**Comment by cgranade** [comment]
Both this failure and the one before it are in unrelated tests. For instance, the most recent failure is in ``qutip.tests.test_fidelity2``, which rather surprises me as I'd have thought that test case was quite stable.

**Comment by cgranade** [comment]
Similar test failures are affecting #429, with ``qutip.tests.test_subsys_apply`` now raising assertion errors.

**Comment by ajgpitch** [comment]
For want of another idea I restarted the tests

**Comment by cgranade** [comment]
Sounds good. I restarted once earlier and it failed on a different test, such that I think we should possibly create a new Issue to help track down which tests are randomly failing and why.

**Comment by ajgpitch** [comment]
Yes, I was thinking the same thing. I will open an issue now.

**Comment by cgranade** [comment]
Sounds good, we should definitely make sure that the tests all work for 3.2
final. In the meantime, I think we should continue to merge in fixes when
its clear that the test failures are unrelated.

**Pull request merged**
