### PR TITLE
Truncation of negative eigenvalues

### PR DESCRIPTION
**Pull request by cgranade**
This PR introduces a new method on``Qobj`` that forces an instance to be a valid density operator. This is useful when dealing with tomographic estimators that do not constrain to the space of density operators, such as least-squares fits. In particular, this PR allows for two different truncation algorithms: ``clip``, which is fast and straightforward, and the [SGS algorithm](https://dx.doi.org/10/bb76).

### CODE REVIEW

**Comment by ajgpitch** [comment]
Looks good to me.
Should the test function have a docstring? I seem to remember these get reported during the testing, although maybe it's different when you use this yield method

**Comment by cgranade** [comment]
That's a good catch, thanks. I'll look at how nostests handles docstrings in cases, but at the least, the test generator should have a docstring, I agree.

**Comment by cgranade** [comment]
That turned out to be surprisingly hairy. This is a total hack, but hopefully one that will be useful in the future.

**Comment by ajgpitch** [comment]
Yes, I see quite involved. Well, looks good now anyway.

**Comment by cgranade** [comment]
I checked locally by intentionally making the tests fail, and the case descriptions do show up in failure logs correctly, so at least the hack works?

**Comment by ajgpitch** [comment]
All looks good and ready to merge to me

**Comment by cgranade** [comment]
Given that this PR worked fine on Travis CI before I merged it, I'm at a loss as to why all of the builds are now erroring out, much less at the linking stage. It's late here, so I'll try and look at it ASAP tomorrow. Thanks for your patience.

**Comment by nonhermitian** [comment]
It is from the mcf90 fortran code.  Since we are testing using Anaconda, it is looking for the MKL library that does not exist.  Therefore, it has nothing to do with the current PR.  I will disable the mcf90 flag that is really worthless anyway since the fortran tests do not run.

**Comment by nonhermitian** [comment]
After fixing the fortran issue here is the error:

======================================================================
ERROR: Test Qobj: trunc_neg works for non-diagonal opers.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/test-environment/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/build/qutip/qutip/qutip/tests/test_qobj.py", line 816, in case
    pos_qobj = qobj.trunc_neg(method=method)
  File "/home/travis/build/qutip/qutip/qutip/qobj.py", line 1246, in trunc_neg
    if eigvals[idx] + acc / (idx + 1) >= 0:
IndexError: index 2 is out of bounds for axis 0 with size 2

**Comment by cgranade** [comment]
Weirdly, that error didn't show up in Travis CI for me before I merged. Working on diagnosing now, thanks for catching it.

**Pull request merged**
