### PR TITLE
Add user defined gates, MS gate and fix some bugs (replacement)

### LINKED ISSUE #819: Defining the Mølmer–Sørensen gate
I know the mathematical definition of the Mølmer–Sørensen gate. How can I define it as a gate in qutip to use in a circuit? Thanks.

### LINKED ISSUE #914: Custom gates for QubitCircuit
At the moment it is possible to make a custom `Gate` and pass it to a `QubitCircuit` so that it will appear on the diagram.
Is it also possible to connect it to an actual operator, so that when  `QubitCircuit.propagators` is called it also returns the propagator of the custom gate?

### PR DESCRIPTION
**Pull request by BoxiLi**
This is a fresh PR branching from the current master as a replacement for #1025 
1. `expand_oper`: expand a qubits operator to dim N
2. User-defined gate can be given by a python function. By passing a list of user-defined gate function to the attribute `QubitCircuit.user_gate`,   `QubitCircuit.propagators()` can return the corresponding matrices. Resolve #914 
3. MS gate and physical single qubit rotation. (Is the name `mc_gate `and `qrot `appropriate?) Resolve #819
4. Fix some bugs in resolving circuit gates. Allow more than one 2-qubits gates in the basis. This is actually already required in `spinchain.py` but covered by a bug

### CODE REVIEW

**Comment by quantshah** [comment]
Surprised to see the term `cognitive complexity in the code` :p 

https://docs.codeclimate.com/docs/cognitive-complexity

**Comment by BoxiLi** [comment]
I guess the purpose is to reduce complexity and increase maintainability. I'm not sure how should I reduce this. Separate the input check and use another private method?

**Comment by nathanshammah** [comment]
Interesting: https://github.com/kowei1995/Molmer-Sorensen-gate

**Comment by BoxiLi** [comment]
@nathanshammah  Yes it's a famous gate. This looks like a decomposition to driving Hamiltonians. Although I don't really understand what is on the y-axis. Could be useful if we want to implement an ion trap processor.

**Comment by nathanshammah** [comment]
Functions run, tests ok on my machine (darwin). Can you add a test for `molmer_sorensen` if appropriate?

**Comment by nathanshammah** [comment]
Played also with qrot and user defined gates and all worked fine.

**Comment by nathanshammah** [comment]
Could add a test for `molmer_sorensen` and then we can merge I think.

**Comment by BoxiLi** [comment]
@nathanshammah Sure, I can add a test for it. Just I'm not sure what should I test against? If I compare the result matrix, I'm basically just copying the matrix from the code. Test on high dimension?

**Comment by nathanshammah** [comment]
Yes, something very simple would work, I guess. 

```
from numpy.testing import assert_,assert_almost_equal
assert_(molmer_sorensen(0)==tensor(qeye(2),qeye(2)))
assert_almost_equal(molmer_sorensen(np.pi/2).full(),Qobj(np.array([[0.70710678+0.j        , 0.        +0.j        ,
        0.        +0.j        , 0.        -0.70710678j],
       [0.        +0.j        , 0.70710678+0.j        ,
        0.        -0.70710678j, 0.        +0.j        ],
       [0.        +0.j        , 0.        -0.70710678j,
        0.70710678+0.j        , 0.        +0.j        ],
       [0.        -0.70710678j, 0.        +0.j        ,
        0.        +0.j        , 0.70710678+0.j        ]]),dims=tensor(qeye(2),qeye(2)).dims))
```
and something for N>3 if needed.

**Pull request merged**
