### PR TITLE
ENH: About updates

### PR DESCRIPTION
**Pull request by nonhermitian**
- hardware_info now detects # of physical cpus under Win.
- about() and version_table() now display BLAS type.

### CODE REVIEW

**Comment by ajgpitch** [comment]
Generally looks like a really good idea.

Are either of these libraries that Python windows users would have installed anyway? Are they in the default Anaconda for windows for instance?

**Comment by cgranade** [comment]
I only had ``comtypes`` installed for something else, but at least it's in conda and pip. Sadly, ``win32com`` is not in either repository.

**Comment by ajgpitch** [comment]
I which case I think we should definitely use the comtypes as Chris suggests. And add it to the recommended packages in the install docs

**Comment by nonhermitian** [comment]
Win32com is in win Anaconda. That is how I tested the code.

**Comment by nonhermitian** [comment]
I will recode tonight

**Comment by ajgpitch** [comment]
Well, I suppose it makes sense to try both then, and hope one gives an answer.

**Comment by cgranade** [comment]
I didn't realize it was in current versions of Anaconda, sorry, as it
didn't use to be on 64-bit. My sincere apologies.

**Comment by ajgpitch** [comment]
Is everyone happy with this now? I am quite keen to get a version out there which fixes the version_table.

**Comment by ajgpitch** [comment]
@nonhermitian it seems this now has conflicts and cannot merged

**Comment by nonhermitian** [comment]
This no longer has any conflicts.  However, as usual, the errors are generated by qutip.tests.test_subsys_apply as given in Issue #430.

**Pull request merged**
