### PR TITLE
Remove star import in tests

### PR DESCRIPTION
**Pull request by ajgpitch**
Only test_mcsolve done for now.

### CODE REVIEW

**Comment by ajgpitch** [comment]
When running nosetest with just test_mcsolve in a folder, on Windows, I found that somehow the tests appeared to respawn recursively. For some reason this change seemed to fix that problem.

**Comment by ajgpitch** [comment]
There are ten other test files with `from qutip import *`. I will fix these soon, as this may fix the problem we are experiencing with tests on Windows with the release we are trying to make

**Comment by ajgpitch** [comment]
It seems that #729 fixed the strange recursively calling of the tests mentioned above. Hence I will close this as it has nothing to offer

**Comment by sahmed95** [comment]
Just an observation, in a lot of places I have seen the use of `from qutip import *` (examples, code) which is supposed to be a bad practice. Should we open an issue to clean that up ?

**Comment by ajgpitch** [comment]
I think we should open up an issue to discuss it. I am keen that we remove them

**Comment by ajgpitch** [comment]
But perhaps we should do it in small PRs like this one, rather than one big one

**Pull request closed without merging**
