### PR TITLE
Bloch-Redfield master equation solver for time-dependent Hamiltonians and c_ops

### PR DESCRIPTION
**Pull request by kafischer**
Implemented a time-dependent version of the Bloch-Redfield master equation solver for time-dependent Hamiltonians and c_ops. It makes use of the list array format.

Also fixed some formatting inconsistencies in the correlation docstrings (yet again... I think I got it this time)

### CODE REVIEW

**Comment by kafischer** [comment]
I make an example jupyter notebook showing this functionality and started a pull on qutip/qutip-notebooks for it

https://github.com/qutip/qutip-notebooks/pull/34

**Comment by nonhermitian** [comment]
This looks good.  I will look at merging this tonight.  I think it would be nice to have a more general time-dependent method as well.  I have a function based version working, but not a string one.  I will look at trying to implement this sometime this week.

**Comment by kafischer** [comment]
Great, thanks!

**Comment by nonhermitian** [comment]
This looks good except for the documentation changes in correlation.  They seem not to satisfy the usual NumPy doc conventions.  For example ``list``, ``numpy.array`` should be listed as array_like per the usual notation (unless this has changed without my knowing).  As a general rule, separate changes, such as the brsolver changes and correlation changes, should be split into different pull requests as well.

**Comment by kafischer** [comment]
My apologies, you're absolutely correct.

Yes, I should have done that  - I accidentally got carried away when I realized that the format of the docstrings in the two modules was completely different.

**Comment by kafischer** [comment]
@nonhermitian 

Hi Paul, I'm a bit confused - is there something else you're waiting for me to change?

thanks!

**Comment by nonhermitian** [comment]
Nope, my point is that we should have a full-blown time dependent brsolver before we have approximate versions. If anything just for comparison, and if someone wants to do the whole sim. I can write it, but time is the issue. I am trying to have a bunch of these things done before I go meet everyone in Japan to work on the PRX paper and what not.

**Comment by kafischer** [comment]
I'm a bit confused on that and I'm sure it will make sense after you write this, but would you mind explaining how that works - are you diagonalizing the time-dependent bloch-redfield tensor in the cythonized version of the function?

**Comment by nonhermitian** [comment]
You need to diagonalize the hamiltonian at each each time step, change the bases for the a-ops, and build the tensor. You have to change the basis of the vector to the eigenbasis and back again as well.

**Comment by kafischer** [comment]
Sure, but I suppose I meant: are you planning to integrate that process in the ODE passed to the scipy integrator?

**Comment by nonhermitian** [comment]
Yep. Can all be done in the rhs function call.

**Comment by kafischer** [comment]
cool, thanks!

**Comment by kafischer** [comment]
Hi Paul, I have some free time so I was thinking that if you're not currently working on this I'll try to put it together (the full time-dependent solver). Thanks

**Comment by nonhermitian** [comment]
Mine will be done in a week or so, depending on time.

**Comment by nonhermitian** [comment]
There are always other things if your interested.

**Comment by nonhermitian** [comment]
This is superseded by #676.

**Pull request closed without merging**
