### PR TITLE
fix - semidefinite cvxpy Variable and Parameter

### PR DESCRIPTION
**Pull request by ajgpitch**
cvxpy Variable and Parameter dims passed as tuple
cvxpy and its depends only installed in tests for NOMKL builds
Extra test added for NOMKL with OPENMP

### CODE REVIEW

**Comment by ajgpitch** [comment]
Attempted fix for #872

**Comment by sahmed95** [comment]
Thanks for this. Merging now.

**Comment by ajgpitch** [comment]
@sahmed95 I am assuming that tests passed then? 
I can't find any Travis record of them having run.

**Comment by sahmed95** [comment]
Yes, the tests ran locally on a test environment I had created. The metrics test ran fine on Travis indirectly on this other PR : https://travis-ci.org/qutip/qutip/builds/379109476. 

Note that the python 2.7 failures are not related but are of similar nature with something changing for supplying arguments in tuples vs directly passing them. However, in hindsight, I should have rebuild on this PR. But I could find no way of re-starting the tests here as travis didn;t see any change to trigger a new test. I will test this with a fresh PR.

**Comment by sahmed95** [comment]
Testing the master on: https://travis-ci.org/qutip/qutip

**Comment by ajgpitch** [comment]
Ok, seems like everything is super fragile at the mo.

Can't see the extra test I added running.
NOMKL=1 OPENMP=1
Does anything else need to be done, other than editing the .travis.yml?

**Comment by sahmed95** [comment]
You are right. The travis.yml could not be parsed in the last PRs you made: https://travis-ci.org/qutip/qutip/requests

**Comment by sahmed95** [comment]
There are conda versions for cvxopt and cvxpy (https://anaconda.org/mcg/cvxpy) but nobody seems to be maintaining or updating them. Installing the conda version downgrades everything else. I will first try to fix the yml issue. Nothing seemed to be incorrect in the YML file, and the travis CI linter is not available, so I am not sure what is wrong with the file. Will update if I make progress.

**Comment by ajgpitch** [comment]
Yes, I also tried using these packages. If you see #484 and all the
corresponding links you will see why we switched to the pip install.

It's questionable whether we should have a feature that relies on a library
that is not maintaining a conda package. But that is a question for another
day.

**Comment by sahmed95** [comment]
There is an issue in the travis yml file. Attempting to fix this.

**Pull request merged**
