### PR TITLE
Qtrl data check and dump

### PR DESCRIPTION
**Pull request by ajgpitch**
Unitarity checking added for propagators of time evolution
dumping of transient calculation operators added
generation of summaries for pulse optimisation iterations and system evolution computations added

### CODE REVIEW

**Comment by ajgpitch** [comment]
Initially started to investigate #477 
Found that work proposed in #371 would be very helpful, decided to bite the bullet and get it done.
This also contains the fix #476

**Comment by ajgpitch** [comment]
Need to add unitarity checking and data dumping into some tests. 
Also, will squash commits before merging.

**Comment by ajgpitch** [comment]
The dumping tests were mainly added to increase coverage
The unitarity test would have caught #477

**Comment by ajgpitch** [comment]
I have rebased to pick up all the recent bug fixes.  Hopefully this will mean this will pass all the tests now.
I have been using the new features quite a lot, so I will squash and merge if this passes the tests.

**Comment by ajgpitch** [comment]
After a few attempts I found that I was unable to successfully squash any commits here. Perhaps I should have done it before rebasing from master? I think I am in danger of doing more harm than good through my squashing, so I will just merge this as it is unless anyone objects.

**Comment by nonhermitian** [comment]
There is a squash merge option when you merge.

**Pull request merged**
