### PR TITLE
qobj isunitary attrib

### PR DESCRIPTION
**Pull request by ajgpitch**
add isunitary attribute for checking if qobj is a unitary operator:
unitary checking func and property funcs added
initialisation of isunitary
clear flag on operations that risk unitarity
qobj unitarity testing added
preset isunitary for qeye

### CODE REVIEW

**Comment by ajgpitch** [comment]
Nothing too clever here. As in cached flag cleared whenever unitarity threatened
The check could probably be more efficient, but as not expected to be used intensively, then this would seem acceptable.

**Comment by nonhermitian** [comment]
Formally you need to check U*U.dag and U.dag*U.  There is a more optimal way of doing this by slighly modifying the zcsr_mult routine, but may not be worth the effort.

**Comment by ajgpitch** [comment]
Thanks @nonhermitian. I will add the other check.
Its not immediately apparent to me what I can do with zcsr_mult to optimise things. Do you mean have a routine like (pseudo code?):
```
zcsr_mult_adj(A):
    return A*A.dag()

```

**Comment by nonhermitian** [comment]
I mean you can do the check without doing the full multiplication by manipulating the sparse structure itself.

**Comment by nonhermitian** [comment]
Again, not straight forward, but would be faster.

**Comment by ajgpitch** [comment]
As I am only planning to use this in solver setup, then I think this will be faster enough.
Hence merging now.

**Pull request merged**
