### PR TITLE
[WIP] Support for emitting QIR for circuit objects

### PR DESCRIPTION
**Pull request by cgranade**
**Checklist**
Thank you for contributing to QuTiP! Please make sure you have finished the following tasks before opening the PR.

- [x] Please read [Contributing to QuTiP Development](http://qutip.org/docs/latest/development/contributing.html)
- [ ] Contributions to qutip should follow the [pep8 style](https://www.python.org/dev/peps/pep-0008/).
You can use [pycodestyle](http://pycodestyle.pycqa.org/en/latest/index.html) to check your code automatically
- [ ] Please add tests to cover your changes if applicable.
- [ ] If the behavior of the code has changed or new feature has been added, please also update the documentation in the `doc` folder, and the [notebook](https://github.com/qutip/qutip-notebooks). Feel free to ask if you are not sure.

Delete this checklist after you have completed all the tasks. If you have not finished them all, you can also open a [Draft Pull Request](https://github.blog/2019-02-14-introducing-draft-pull-requests/) to let the others know this on-going work and keep this checklist in the PR description.

**Description**
This PR presents a prototype for emitting Quantum Intermediate Representation (QIR) modules from `qutip.qip.QubitCircuit` objects, making it easier to interoperate QuTiP with other quantum software tools and platforms.

The prototype in this PR uses the [PyQIR](https://qir-alliance.github.io/pyqir/) library for Python to handle QIR generation, isolating QIR generation functionality as an optional dependency. 

**Changelog**

-  Support for emitting QIR from circuit objects.

### CODE REVIEW

**Comment by cgranade** [comment]
As a quick example of what this could look like, please see the notebook at https://gist.github.com/cgranade/c26fc3fbbe39ac1c455cc0974356c6be.

**Comment by BoxiLi** [comment]
Thanks @cgranade for the PR! You could also consider making this PR to [qutip-qip](https://github.com/qutip/qutip-qip), as the `qutip.qip` module will be removed from the core qutip package from qutip-v5. So likely we won't add any major feature to it.

Everything should work just fine if one replaces `qutip.qip` by `qutip_qip` in the importation statements.

**Comment by cgranade** [comment]
@BoxiLi: Sounds good, thanks for the kind words! I'll go on and move it to the qutip-qip repo, then, to continue the discussion.

**Comment by nathanshammah** [comment]
Thanks @cgranade. What's the timeline to remove `qip` from `qutip/qutip`? Are we waiting the QuTiP 5 release?

**Comment by hodgestar** [comment]
> Thanks @cgranade. @BoxiLi what's the timeline to remove `qip` from `qutip/qutip`? Are we waiting the QuTiP 5 release?

Yes. `qutip.qip` will still be included in QuTiP 4.7, but for QuTiP 5, qutip-qip will need to be installed separately.

**Comment by hodgestar** [comment]
@cgranade Thank you for opening the qutip-qip PR (https://github.com/qutip/qutip-qip/pull/125). I will close this one.

**Comment by cgranade** [comment]
@hodgestar: Thank you!

**Pull request closed without merging**
