### PR TITLE
WIP: Circuit noise in the qip processor 

### PR DESCRIPTION
**Pull request by BoxiLi**
This PR is a follow-up of #1012. It is intended to separate the noise handling from `CircuiProcessor` and create a framework for adding noise into the QIP simulation.

### CODE REVIEW

**Comment by nathanshammah** [comment]
As @BoxiLi noted, Mac tests are passing for this PR. I ran them twice to check and they passed. This would solve issue #963.

**Comment by BoxiLi** [comment]
@nathanshammah I think it has nothing to do with this PR, I didn't change anything in `qobj.py` where the test failed before. I guess it might have something to do with Erig's commit "mac without mkl" and I simply merged it from master.

**Comment by BoxiLi** [comment]
There is no need to resolve those conflicts now, I'll create a separate PR to master for those change related to `qip/gates` etc.

**Comment by BoxiLi** [comment]
Close because of #1065

**Pull request closed without merging**
