### PR TITLE
Update Readme

### PR DESCRIPTION
**Pull request by nathanshammah**
**Changelog**
Update readme adding Boxi Li to authors and badges of NumFOUCS and Unitary Fund.

### CODE REVIEW

**Comment by nathanshammah** [comment]
@BoxiLi sorry I did not understand.

**Comment by Ericgig** [comment]
Adding NumFOCUS and Unitary Fund on the readme without mentioning RIKEN, Sherbrooke U., Aberystwyth U. seems strange to me.

**Comment by nathanshammah** [comment]
@ericgig you're right. I have added to this [pull request](https://github.com/qutip/qutip.github.io/pull/114) (114 in qutip.github.io) a new anchor next to the headings #supporting-organizations, and I then wanted to add a link to it here. It could also mention them (or a subset of those listed there) also here, without logos but in writing.  

If someone can review that PR 114, I can then modify this one more easily.

**Comment by BoxiLi** [comment]
> @BoxiLi sorry I did not understand.

Nothing important, I was just wondering why do you add `qutip/qutip-gsoc-2020.md` here? The content is the same as on the wiki page right?

**Comment by nathanshammah** [comment]
@BoxiLi, thanks. I wanted to create a project page or something and then forgot. Will keep this feature proposal for another time.

**Comment by Ericgig** [comment]
The `qutip-gsoc-2020.md` page should not be in the code folder. And since GSoC2020 application period has passed, I don't believe it is needed at all.

**Comment by nathanshammah** [comment]
@Ericgig it's been removed.

**Pull request merged**
